# Form implementation generated from reading ui file 'ui/aboutdialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# Automatically generated - do not edit.
# Use `python setup.py build_ui` to update it.

from PyQt6 import (
    QtCore,
    QtGui,
    QtWidgets,
)

from picard.i18n import gettext as _


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(680, 861)
        AboutDialog.setMinimumSize(QtCore.QSize(420, 360))
        self.main_layout = QtWidgets.QVBoxLayout(AboutDialog)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.scrollArea = QtWidgets.QScrollArea(parent=AboutDialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 680, 861))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.content_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.content_layout.setContentsMargins(32, 24, 32, 24)
        self.content_layout.setSpacing(16)
        self.content_layout.setObjectName("content_layout")
        self.header_layout = QtWidgets.QVBoxLayout()
        self.header_layout.setSpacing(4)
        self.header_layout.setObjectName("header_layout")
        self.logo_name_layout = QtWidgets.QHBoxLayout()
        self.logo_name_layout.setSpacing(12)
        self.logo_name_layout.setObjectName("logo_name_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logo_name_layout.addItem(spacerItem)
        self.logo = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(64, 64))
        self.logo.setMaximumSize(QtCore.QSize(64, 64))
        self.logo.setPixmap(QtGui.QPixmap(":/images/128x128/org.musicbrainz.Picard.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.logo_name_layout.addWidget(self.logo)
        self.app_name = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_name.sizePolicy().hasHeightForWidth())
        self.app_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.app_name.setFont(font)
        self.app_name.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.app_name.setObjectName("app_name")
        self.logo_name_layout.addWidget(self.app_name)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logo_name_layout.addItem(spacerItem1)
        self.header_layout.addLayout(self.logo_name_layout)
        self.version_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.version_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.version_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.version_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.version_label.setObjectName("version_label")
        self.header_layout.addWidget(self.version_label)
        self.versions_detail_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.versions_detail_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.versions_detail_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.versions_detail_label.setWordWrap(True)
        self.versions_detail_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.versions_detail_label.setObjectName("versions_detail_label")
        self.header_layout.addWidget(self.versions_detail_label)
        self.content_layout.addLayout(self.header_layout)
        self.separator_1 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.separator_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.separator_1.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.separator_1.setObjectName("separator_1")
        self.content_layout.addWidget(self.separator_1)
        self.formats_layout = QtWidgets.QVBoxLayout()
        self.formats_layout.setSpacing(6)
        self.formats_layout.setObjectName("formats_layout")
        self.formats_heading = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        self.formats_heading.setFont(font)
        self.formats_heading.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.formats_heading.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.formats_heading.setObjectName("formats_heading")
        self.formats_layout.addWidget(self.formats_heading)
        self.formats_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.formats_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.formats_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.formats_label.setWordWrap(True)
        self.formats_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.formats_label.setObjectName("formats_label")
        self.formats_layout.addWidget(self.formats_label)
        self.content_layout.addLayout(self.formats_layout)
        self.separator_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.separator_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.separator_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.separator_2.setObjectName("separator_2")
        self.content_layout.addWidget(self.separator_2)
        self.donate_layout = QtWidgets.QVBoxLayout()
        self.donate_layout.setSpacing(10)
        self.donate_layout.setObjectName("donate_layout")
        self.donate_heading = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        self.donate_heading.setFont(font)
        self.donate_heading.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.donate_heading.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.donate_heading.setObjectName("donate_heading")
        self.donate_layout.addWidget(self.donate_heading)
        self.donate_text_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.donate_text_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.donate_text_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.donate_text_label.setWordWrap(True)
        self.donate_text_label.setObjectName("donate_text_label")
        self.donate_layout.addWidget(self.donate_text_label)
        self.donate_button_layout = QtWidgets.QHBoxLayout()
        self.donate_button_layout.setObjectName("donate_button_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.donate_button_layout.addItem(spacerItem2)
        self.donate_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.donate_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.donate_button.setObjectName("donate_button")
        self.donate_button_layout.addWidget(self.donate_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.donate_button_layout.addItem(spacerItem3)
        self.donate_layout.addLayout(self.donate_button_layout)
        self.content_layout.addLayout(self.donate_layout)
        self.separator_3 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.separator_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.separator_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.separator_3.setObjectName("separator_3")
        self.content_layout.addWidget(self.separator_3)
        self.credits_layout = QtWidgets.QVBoxLayout()
        self.credits_layout.setSpacing(6)
        self.credits_layout.setObjectName("credits_layout")
        self.credits_heading = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        self.credits_heading.setFont(font)
        self.credits_heading.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.credits_heading.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.credits_heading.setObjectName("credits_heading")
        self.credits_layout.addWidget(self.credits_heading)
        self.project_credit_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.project_credit_label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.project_credit_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.project_credit_label.setWordWrap(True)
        self.project_credit_label.setOpenExternalLinks(True)
        self.project_credit_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.project_credit_label.setObjectName("project_credit_label")
        self.credits_layout.addWidget(self.project_credit_label)
        self.copyright_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.copyright_label.setText("COPYRIGHT")
        self.copyright_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.copyright_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.copyright_label.setWordWrap(True)
        self.copyright_label.setObjectName("copyright_label")
        self.credits_layout.addWidget(self.copyright_label)
        self.translator_credits = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.translator_credits.setObjectName("translator_credits")
        self.translator_credits_layout = QtWidgets.QVBoxLayout(self.translator_credits)
        self.translator_credits_layout.setContentsMargins(0, 0, 0, 0)
        self.translator_credits_layout.setObjectName("translator_credits_layout")
        self.translator_credits_label = QtWidgets.QLabel(parent=self.translator_credits)
        self.translator_credits_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.translator_credits_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.translator_credits_label.setWordWrap(True)
        self.translator_credits_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.translator_credits_label.setObjectName("translator_credits_label")
        self.translator_credits_layout.addWidget(self.translator_credits_label)
        self.translate_button_layout = QtWidgets.QHBoxLayout()
        self.translate_button_layout.setObjectName("translate_button_layout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.translate_button_layout.addItem(spacerItem4)
        self.translate_button = QtWidgets.QPushButton(parent=self.translator_credits)
        self.translate_button.setObjectName("translate_button")
        self.translate_button_layout.addWidget(self.translate_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.translate_button_layout.addItem(spacerItem5)
        self.translator_credits_layout.addLayout(self.translate_button_layout)
        self.credits_layout.addWidget(self.translator_credits)
        self.icons_credits_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.icons_credits_label.setText("ICONS_CREDITS")
        self.icons_credits_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.icons_credits_label.setWordWrap(True)
        self.icons_credits_label.setOpenExternalLinks(True)
        self.icons_credits_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.icons_credits_label.setObjectName("icons_credits_label")
        self.credits_layout.addWidget(self.icons_credits_label)
        self.content_layout.addLayout(self.credits_layout)
        self.separator_4 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.separator_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.separator_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.separator_4.setObjectName("separator_4")
        self.content_layout.addWidget(self.separator_4)
        self.website_layout = QtWidgets.QVBoxLayout()
        self.website_layout.setSpacing(6)
        self.website_layout.setObjectName("website_layout")
        self.website_heading = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        self.website_heading.setFont(font)
        self.website_heading.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.website_heading.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.website_heading.setObjectName("website_heading")
        self.website_layout.addWidget(self.website_heading)
        self.website_link_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.website_link_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.website_link_label.setOpenExternalLinks(True)
        self.website_link_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.website_link_label.setObjectName("website_link_label")
        self.website_layout.addWidget(self.website_link_label)
        self.content_layout.addLayout(self.website_layout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.content_layout.addItem(spacerItem6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.main_layout.addWidget(self.scrollArea)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        AboutDialog.setWindowTitle(_("About Picard"))
        self.app_name.setText(_("MusicBrainz Picard"))
        self.formats_heading.setText(_("Supported formats"))
        self.donate_heading.setText(_("Please donate"))
        self.donate_text_label.setText(_("Thank you for using Picard. Picard relies on the MusicBrainz database, which is operated by the MetaBrainz Foundation with the help of thousands of volunteers. If you like this application please consider donating to the MetaBrainz Foundation to keep the service running."))
        self.donate_button.setText(_("Donate now!"))
        self.credits_heading.setText(_("Credits"))
        self.project_credit_label.setText(_("A <a href=\"https://metabrainz.org\">MetaBrainz Foundation</a> project, powered by the <a href=\"https://musicbrainz.org\">MusicBrainz</a> database."))
        self.translator_credits_label.setText(_("Translated by the MusicBrainz community. Thank you to everyone who helps make Picard available in more languages!"))
        self.translate_button.setText(_("Help with translation"))
        self.website_heading.setText(_("Links"))
