# Form implementation generated from reading ui file 'ui/infostatus.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# Automatically generated - do not edit.
# Use `python setup.py build_ui` to update it.

from PyQt6 import (
    QtCore,
    QtGui,
    QtWidgets,
)

from picard.i18n import gettext as _


class Ui_InfoStatus(object):
    def setupUi(self, InfoStatus):
        InfoStatus.setObjectName("InfoStatus")
        InfoStatus.resize(683, 145)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InfoStatus.sizePolicy().hasHeightForWidth())
        InfoStatus.setSizePolicy(sizePolicy)
        InfoStatus.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayout = QtWidgets.QHBoxLayout(InfoStatus)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.eta_value = QtWidgets.QLabel(parent=InfoStatus)
        self.eta_value.setMinimumSize(QtCore.QSize(40, 0))
        self.eta_value.setText("")
        self.eta_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.eta_value.setObjectName("eta_value")
        self.horizontalLayout.addWidget(self.eta_value)
        self.eta_icon = QtWidgets.QLabel(parent=InfoStatus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eta_icon.sizePolicy().hasHeightForWidth())
        self.eta_icon.setSizePolicy(sizePolicy)
        self.eta_icon.setMinimumSize(QtCore.QSize(0, 0))
        self.eta_icon.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.eta_icon.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.eta_icon.setScaledContents(False)
        self.eta_icon.setObjectName("eta_icon")
        self.horizontalLayout.addWidget(self.eta_icon)
        self.files_value = QtWidgets.QLabel(parent=InfoStatus)
        self.files_value.setMinimumSize(QtCore.QSize(40, 0))
        self.files_value.setText("")
        self.files_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.files_value.setObjectName("files_value")
        self.horizontalLayout.addWidget(self.files_value)
        self.files_icon = QtWidgets.QLabel(parent=InfoStatus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.files_icon.sizePolicy().hasHeightForWidth())
        self.files_icon.setSizePolicy(sizePolicy)
        self.files_icon.setText("")
        self.files_icon.setObjectName("files_icon")
        self.horizontalLayout.addWidget(self.files_icon)
        self.albums_value = QtWidgets.QLabel(parent=InfoStatus)
        self.albums_value.setMinimumSize(QtCore.QSize(40, 0))
        self.albums_value.setText("")
        self.albums_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.albums_value.setObjectName("albums_value")
        self.horizontalLayout.addWidget(self.albums_value)
        self.albums_icon = QtWidgets.QLabel(parent=InfoStatus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.albums_icon.sizePolicy().hasHeightForWidth())
        self.albums_icon.setSizePolicy(sizePolicy)
        self.albums_icon.setText("")
        self.albums_icon.setObjectName("albums_icon")
        self.horizontalLayout.addWidget(self.albums_icon)
        self.pending_files_value = QtWidgets.QLabel(parent=InfoStatus)
        self.pending_files_value.setMinimumSize(QtCore.QSize(40, 0))
        self.pending_files_value.setText("")
        self.pending_files_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pending_files_value.setObjectName("pending_files_value")
        self.horizontalLayout.addWidget(self.pending_files_value)
        self.pending_files_icon = QtWidgets.QLabel(parent=InfoStatus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pending_files_icon.sizePolicy().hasHeightForWidth())
        self.pending_files_icon.setSizePolicy(sizePolicy)
        self.pending_files_icon.setText("")
        self.pending_files_icon.setScaledContents(False)
        self.pending_files_icon.setObjectName("pending_files_icon")
        self.horizontalLayout.addWidget(self.pending_files_icon)
        self.pending_requests_value = QtWidgets.QLabel(parent=InfoStatus)
        self.pending_requests_value.setMinimumSize(QtCore.QSize(40, 0))
        self.pending_requests_value.setText("")
        self.pending_requests_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pending_requests_value.setObjectName("pending_requests_value")
        self.horizontalLayout.addWidget(self.pending_requests_value)
        self.pending_requests_icon = QtWidgets.QLabel(parent=InfoStatus)
        self.pending_requests_icon.setMinimumSize(QtCore.QSize(0, 0))
        self.pending_requests_icon.setText("")
        self.pending_requests_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pending_requests_icon.setObjectName("pending_requests_icon")
        self.horizontalLayout.addWidget(self.pending_requests_icon)
        self.stop_button = QtWidgets.QToolButton(parent=InfoStatus)
        self.stop_button.setMinimumSize(QtCore.QSize(0, 0))
        self.stop_button.setText("")
        self.stop_button.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.stop_button.setAutoRaise(True)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)

        self.retranslateUi(InfoStatus)
        QtCore.QMetaObject.connectSlotsByName(InfoStatus)

    def retranslateUi(self, InfoStatus):
        InfoStatus.setWindowTitle(_("Form"))
