# Form implementation generated from reading ui file 'ui/options_fingerprinting.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# Automatically generated - do not edit.
# Use `python setup.py build_ui` to update it.

from PyQt6 import (
    QtCore,
    QtGui,
    QtWidgets,
)

from picard.i18n import gettext as _


class Ui_FingerprintingOptionsPage(object):
    def setupUi(self, FingerprintingOptionsPage):
        FingerprintingOptionsPage.setObjectName("FingerprintingOptionsPage")
        FingerprintingOptionsPage.resize(371, 408)
        self.verticalLayout = QtWidgets.QVBoxLayout(FingerprintingOptionsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fingerprinting = QtWidgets.QGroupBox(parent=FingerprintingOptionsPage)
        self.fingerprinting.setCheckable(False)
        self.fingerprinting.setObjectName("fingerprinting")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fingerprinting)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.disable_fingerprinting = QtWidgets.QRadioButton(parent=self.fingerprinting)
        self.disable_fingerprinting.setObjectName("disable_fingerprinting")
        self.verticalLayout_3.addWidget(self.disable_fingerprinting)
        self.use_acoustid = QtWidgets.QRadioButton(parent=self.fingerprinting)
        self.use_acoustid.setObjectName("use_acoustid")
        self.verticalLayout_3.addWidget(self.use_acoustid)
        self.verticalLayout.addWidget(self.fingerprinting)
        self.acoustid_settings = QtWidgets.QGroupBox(parent=FingerprintingOptionsPage)
        self.acoustid_settings.setObjectName("acoustid_settings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.acoustid_settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ignore_existing_acoustid_fingerprints = QtWidgets.QCheckBox(parent=self.acoustid_settings)
        self.ignore_existing_acoustid_fingerprints.setObjectName("ignore_existing_acoustid_fingerprints")
        self.verticalLayout_2.addWidget(self.ignore_existing_acoustid_fingerprints)
        self.save_acoustid_fingerprints = QtWidgets.QCheckBox(parent=self.acoustid_settings)
        self.save_acoustid_fingerprints.setObjectName("save_acoustid_fingerprints")
        self.verticalLayout_2.addWidget(self.save_acoustid_fingerprints)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.maximum_threads_label = QtWidgets.QLabel(parent=self.acoustid_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximum_threads_label.sizePolicy().hasHeightForWidth())
        self.maximum_threads_label.setSizePolicy(sizePolicy)
        self.maximum_threads_label.setObjectName("maximum_threads_label")
        self.horizontalLayout_3.addWidget(self.maximum_threads_label)
        self.fpcalc_threads = QtWidgets.QSpinBox(parent=self.acoustid_settings)
        self.fpcalc_threads.setMinimum(1)
        self.fpcalc_threads.setMaximum(9)
        self.fpcalc_threads.setObjectName("fpcalc_threads")
        self.horizontalLayout_3.addWidget(self.fpcalc_threads)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.fingerprint_calculator_label = QtWidgets.QLabel(parent=self.acoustid_settings)
        self.fingerprint_calculator_label.setObjectName("fingerprint_calculator_label")
        self.verticalLayout_2.addWidget(self.fingerprint_calculator_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.acoustid_fpcalc = QtWidgets.QLineEdit(parent=self.acoustid_settings)
        self.acoustid_fpcalc.setObjectName("acoustid_fpcalc")
        self.horizontalLayout_2.addWidget(self.acoustid_fpcalc)
        self.acoustid_fpcalc_browse = QtWidgets.QToolButton(parent=self.acoustid_settings)
        self.acoustid_fpcalc_browse.setObjectName("acoustid_fpcalc_browse")
        self.horizontalLayout_2.addWidget(self.acoustid_fpcalc_browse)
        self.acoustid_fpcalc_download = QtWidgets.QPushButton(parent=self.acoustid_settings)
        self.acoustid_fpcalc_download.setObjectName("acoustid_fpcalc_download")
        self.horizontalLayout_2.addWidget(self.acoustid_fpcalc_download)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.acoustid_fpcalc_info = QtWidgets.QLabel(parent=self.acoustid_settings)
        self.acoustid_fpcalc_info.setText("")
        self.acoustid_fpcalc_info.setObjectName("acoustid_fpcalc_info")
        self.verticalLayout_2.addWidget(self.acoustid_fpcalc_info)
        self.api_key_label = QtWidgets.QLabel(parent=self.acoustid_settings)
        self.api_key_label.setObjectName("api_key_label")
        self.verticalLayout_2.addWidget(self.api_key_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acoustid_apikey = QtWidgets.QLineEdit(parent=self.acoustid_settings)
        self.acoustid_apikey.setObjectName("acoustid_apikey")
        self.horizontalLayout.addWidget(self.acoustid_apikey)
        self.acoustid_apikey_get = QtWidgets.QPushButton(parent=self.acoustid_settings)
        self.acoustid_apikey_get.setObjectName("acoustid_apikey_get")
        self.horizontalLayout.addWidget(self.acoustid_apikey_get)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.acoustid_settings)
        spacerItem = QtWidgets.QSpacerItem(181, 21, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.maximum_threads_label.setBuddy(self.fpcalc_threads)
        self.fingerprint_calculator_label.setBuddy(self.acoustid_fpcalc)
        self.api_key_label.setBuddy(self.acoustid_apikey)

        self.retranslateUi(FingerprintingOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(FingerprintingOptionsPage)

    def retranslateUi(self, FingerprintingOptionsPage):
        self.fingerprinting.setTitle(_("Audio Fingerprinting"))
        self.disable_fingerprinting.setText(_("Do not use audio fingerprinting"))
        self.use_acoustid.setText(_("Use AcoustID"))
        self.acoustid_settings.setTitle(_("AcoustID Settings"))
        self.ignore_existing_acoustid_fingerprints.setText(_("Ignore existing AcoustID fingerprints"))
        self.save_acoustid_fingerprints.setText(_("Save AcoustID fingerprints to file tags"))
        self.maximum_threads_label.setText(_("Maximum threads to use for calculator:"))
        self.fingerprint_calculator_label.setText(_("Fingerprint calculator:"))
        self.acoustid_fpcalc_browse.setToolTip(_("Select file"))
        self.acoustid_fpcalc_download.setText(_("Download…"))
        self.api_key_label.setText(_("API key:"))
        self.acoustid_apikey_get.setText(_("Get API key…"))
