# Form implementation generated from reading ui file 'ui/options_matching.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# Automatically generated - do not edit.
# Use `python setup.py build_ui` to update it.

from PyQt6 import (
    QtCore,
    QtGui,
    QtWidgets,
)

from picard.i18n import gettext as _


class Ui_MatchingOptionsPage(object):
    def setupUi(self, MatchingOptionsPage):
        MatchingOptionsPage.setObjectName("MatchingOptionsPage")
        MatchingOptionsPage.resize(413, 612)
        self.vboxlayout = QtWidgets.QVBoxLayout(MatchingOptionsPage)
        self.vboxlayout.setObjectName("vboxlayout")
        self.matching_group = QtWidgets.QGroupBox(parent=MatchingOptionsPage)
        self.matching_group.setObjectName("matching_group")
        self.gridlayout = QtWidgets.QGridLayout(self.matching_group)
        self.gridlayout.setSpacing(2)
        self.gridlayout.setObjectName("gridlayout")
        self.label_min_similarity = QtWidgets.QLabel(parent=self.matching_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_similarity.sizePolicy().hasHeightForWidth())
        self.label_min_similarity.setSizePolicy(sizePolicy)
        self.label_min_similarity.setObjectName("label_min_similarity")
        self.gridlayout.addWidget(self.label_min_similarity, 0, 0, 1, 1)
        self.match_min_similarity = QtWidgets.QSpinBox(parent=self.matching_group)
        self.match_min_similarity.setMaximum(100)
        self.match_min_similarity.setObjectName("match_min_similarity")
        self.gridlayout.addWidget(self.match_min_similarity, 0, 1, 1, 1)
        self.label_min_margin = QtWidgets.QLabel(parent=self.matching_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_margin.sizePolicy().hasHeightForWidth())
        self.label_min_margin.setSizePolicy(sizePolicy)
        self.label_min_margin.setObjectName("label_min_margin")
        self.gridlayout.addWidget(self.label_min_margin, 1, 0, 1, 1)
        self.match_min_margin = QtWidgets.QSpinBox(parent=self.matching_group)
        self.match_min_margin.setMaximum(100)
        self.match_min_margin.setObjectName("match_min_margin")
        self.gridlayout.addWidget(self.match_min_margin, 1, 1, 1, 1)
        self.label_track_matching = QtWidgets.QLabel(parent=self.matching_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_track_matching.sizePolicy().hasHeightForWidth())
        self.label_track_matching.setSizePolicy(sizePolicy)
        self.label_track_matching.setObjectName("label_track_matching")
        self.gridlayout.addWidget(self.label_track_matching, 2, 0, 1, 1)
        self.track_matching_threshold = QtWidgets.QSpinBox(parent=self.matching_group)
        self.track_matching_threshold.setMaximum(100)
        self.track_matching_threshold.setObjectName("track_matching_threshold")
        self.gridlayout.addWidget(self.track_matching_threshold, 2, 1, 1, 1)
        self.label_track_duration_diff = QtWidgets.QLabel(parent=self.matching_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_track_duration_diff.sizePolicy().hasHeightForWidth())
        self.label_track_duration_diff.setSizePolicy(sizePolicy)
        self.label_track_duration_diff.setObjectName("label_track_duration_diff")
        self.gridlayout.addWidget(self.label_track_duration_diff, 3, 0, 1, 1)
        self.ignore_track_duration_difference_under = QtWidgets.QSpinBox(parent=self.matching_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ignore_track_duration_difference_under.sizePolicy().hasHeightForWidth())
        self.ignore_track_duration_difference_under.setSizePolicy(sizePolicy)
        self.ignore_track_duration_difference_under.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ignore_track_duration_difference_under.setAccelerated(True)
        self.ignore_track_duration_difference_under.setMinimum(1)
        self.ignore_track_duration_difference_under.setMaximum(7200)
        self.ignore_track_duration_difference_under.setProperty("value", 2)
        self.ignore_track_duration_difference_under.setObjectName("ignore_track_duration_difference_under")
        self.gridlayout.addWidget(self.ignore_track_duration_difference_under, 3, 1, 1, 1)
        self.vboxlayout.addWidget(self.matching_group)
        self.groupBox_completeness = QtWidgets.QGroupBox(parent=MatchingOptionsPage)
        self.groupBox_completeness.setObjectName("groupBox_completeness")
        self.completeness_layout = QtWidgets.QVBoxLayout(self.groupBox_completeness)
        self.completeness_layout.setObjectName("completeness_layout")
        self.completeness_ignore_videos = QtWidgets.QCheckBox(parent=self.groupBox_completeness)
        self.completeness_ignore_videos.setObjectName("completeness_ignore_videos")
        self.completeness_layout.addWidget(self.completeness_ignore_videos)
        self.completeness_ignore_pregap = QtWidgets.QCheckBox(parent=self.groupBox_completeness)
        self.completeness_ignore_pregap.setObjectName("completeness_ignore_pregap")
        self.completeness_layout.addWidget(self.completeness_ignore_pregap)
        self.completeness_ignore_data = QtWidgets.QCheckBox(parent=self.groupBox_completeness)
        self.completeness_ignore_data.setObjectName("completeness_ignore_data")
        self.completeness_layout.addWidget(self.completeness_ignore_data)
        self.completeness_ignore_silence = QtWidgets.QCheckBox(parent=self.groupBox_completeness)
        self.completeness_ignore_silence.setObjectName("completeness_ignore_silence")
        self.completeness_layout.addWidget(self.completeness_ignore_silence)
        self.vboxlayout.addWidget(self.groupBox_completeness)
        self.groupBox_ignore_tags = QtWidgets.QGroupBox(parent=MatchingOptionsPage)
        self.groupBox_ignore_tags.setObjectName("groupBox_ignore_tags")
        self.ignore_tags_layout = QtWidgets.QVBoxLayout(self.groupBox_ignore_tags)
        self.ignore_tags_layout.setObjectName("ignore_tags_layout")
        self.compare_ignore_tags = TagListEditor(parent=self.groupBox_ignore_tags)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compare_ignore_tags.sizePolicy().hasHeightForWidth())
        self.compare_ignore_tags.setSizePolicy(sizePolicy)
        self.compare_ignore_tags.setObjectName("compare_ignore_tags")
        self.ignore_tags_layout.addWidget(self.compare_ignore_tags)
        self.vboxlayout.addWidget(self.groupBox_ignore_tags)
        spacerItem = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.label_min_similarity.setBuddy(self.match_min_similarity)
        self.label_min_margin.setBuddy(self.match_min_margin)
        self.label_track_matching.setBuddy(self.track_matching_threshold)
        self.label_track_duration_diff.setBuddy(self.ignore_track_duration_difference_under)

        self.retranslateUi(MatchingOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(MatchingOptionsPage)
        MatchingOptionsPage.setTabOrder(self.match_min_similarity, self.match_min_margin)
        MatchingOptionsPage.setTabOrder(self.match_min_margin, self.track_matching_threshold)
        MatchingOptionsPage.setTabOrder(self.track_matching_threshold, self.ignore_track_duration_difference_under)
        MatchingOptionsPage.setTabOrder(self.ignore_track_duration_difference_under, self.completeness_ignore_videos)
        MatchingOptionsPage.setTabOrder(self.completeness_ignore_videos, self.completeness_ignore_pregap)
        MatchingOptionsPage.setTabOrder(self.completeness_ignore_pregap, self.completeness_ignore_data)
        MatchingOptionsPage.setTabOrder(self.completeness_ignore_data, self.completeness_ignore_silence)

    def retranslateUi(self, MatchingOptionsPage):
        self.matching_group.setTitle(_("Matching"))
        self.label_min_similarity.setText(_("Minimum similarity:"))
        self.match_min_similarity.setSuffix(_(" %"))
        self.label_min_margin.setText(_("Minimum margin between best and second-best match:"))
        self.match_min_margin.setSuffix(_(" %"))
        self.label_track_matching.setText(_("Minimal similarity for matching files to tracks:"))
        self.track_matching_threshold.setSuffix(_(" %"))
        self.label_track_duration_diff.setText(_("Ignore track duration difference under this number of seconds"))
        self.groupBox_completeness.setTitle(_("Ignore the following tracks when determining whether a release is complete:"))
        self.completeness_ignore_videos.setText(_("Video tracks"))
        self.completeness_ignore_pregap.setText(_("Pre-gap tracks"))
        self.completeness_ignore_data.setText(_("Data tracks"))
        self.completeness_ignore_silence.setText(_("Silent tracks"))
        self.groupBox_ignore_tags.setTitle(_("Tags to ignore for comparison:"))
from picard.ui.widgets.taglisteditor import TagListEditor
