# Form implementation generated from reading ui file 'ui/options_general.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# Automatically generated - do not edit.
# Use `python setup.py build_ui` to update it.

from PyQt6 import (
    QtCore,
    QtGui,
    QtWidgets,
)

from picard.i18n import gettext as _


class Ui_GeneralOptionsPage(object):
    def setupUi(self, GeneralOptionsPage):
        GeneralOptionsPage.setObjectName("GeneralOptionsPage")
        GeneralOptionsPage.resize(403, 526)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GeneralOptionsPage.sizePolicy().hasHeightForWidth())
        GeneralOptionsPage.setSizePolicy(sizePolicy)
        self.vboxlayout = QtWidgets.QVBoxLayout(GeneralOptionsPage)
        self.vboxlayout.setObjectName("vboxlayout")
        self.musicbrainz_server_box = QtWidgets.QGroupBox(parent=GeneralOptionsPage)
        self.musicbrainz_server_box.setObjectName("musicbrainz_server_box")
        self.gridlayout = QtWidgets.QGridLayout(self.musicbrainz_server_box)
        self.gridlayout.setSpacing(2)
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtWidgets.QLabel(parent=self.musicbrainz_server_box)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.server_port = QtWidgets.QSpinBox(parent=self.musicbrainz_server_box)
        self.server_port.setMinimum(1)
        self.server_port.setMaximum(65535)
        self.server_port.setProperty("value", 80)
        self.server_port.setObjectName("server_port")
        self.gridlayout.addWidget(self.server_port, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(1, 4, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridlayout.addItem(spacerItem, 2, 0, 1, 1)
        self.server_host = QtWidgets.QComboBox(parent=self.musicbrainz_server_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_host.sizePolicy().hasHeightForWidth())
        self.server_host.setSizePolicy(sizePolicy)
        self.server_host.setEditable(True)
        self.server_host.setObjectName("server_host")
        self.gridlayout.addWidget(self.server_host, 1, 0, 1, 1)
        self.server_host_primary_warning = QtWidgets.QFrame(parent=self.musicbrainz_server_box)
        self.server_host_primary_warning.setStyleSheet("QFrame { background-color: #ffc107; color: black }\n"
"QCheckBox { color: black }")
        self.server_host_primary_warning.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.server_host_primary_warning.setObjectName("server_host_primary_warning")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.server_host_primary_warning)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.server_host_primary_warning)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.use_server_for_submission = QtWidgets.QCheckBox(parent=self.server_host_primary_warning)
        self.use_server_for_submission.setObjectName("use_server_for_submission")
        self.verticalLayout_4.addWidget(self.use_server_for_submission)
        self.gridlayout.addWidget(self.server_host_primary_warning, 3, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(parent=self.musicbrainz_server_box)
        self.label_7.setObjectName("label_7")
        self.gridlayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.vboxlayout.addWidget(self.musicbrainz_server_box)
        self.musicbrainz_account_box = QtWidgets.QGroupBox(parent=GeneralOptionsPage)
        self.musicbrainz_account_box.setObjectName("musicbrainz_account_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.musicbrainz_account_box)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.login_error = QtWidgets.QLabel(parent=self.musicbrainz_account_box)
        self.login_error.setText("")
        self.login_error.setObjectName("login_error")
        self.verticalLayout_3.addWidget(self.login_error)
        self.logged_in = QtWidgets.QLabel(parent=self.musicbrainz_account_box)
        self.logged_in.setText("")
        self.logged_in.setObjectName("logged_in")
        self.verticalLayout_3.addWidget(self.logged_in)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login = QtWidgets.QPushButton(parent=self.musicbrainz_account_box)
        self.login.setObjectName("login")
        self.horizontalLayout.addWidget(self.login)
        self.logout = QtWidgets.QPushButton(parent=self.musicbrainz_account_box)
        self.logout.setObjectName("logout")
        self.horizontalLayout.addWidget(self.logout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.enable_user_collections = QtWidgets.QCheckBox(parent=self.musicbrainz_account_box)
        self.enable_user_collections.setObjectName("enable_user_collections")
        self.verticalLayout_3.addWidget(self.enable_user_collections)
        self.vboxlayout.addWidget(self.musicbrainz_account_box)
        self.general_box = QtWidgets.QGroupBox(parent=GeneralOptionsPage)
        self.general_box.setObjectName("general_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.general_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.analyze_new_files = QtWidgets.QCheckBox(parent=self.general_box)
        self.analyze_new_files.setObjectName("analyze_new_files")
        self.verticalLayout.addWidget(self.analyze_new_files)
        self.cluster_new_files = QtWidgets.QCheckBox(parent=self.general_box)
        self.cluster_new_files.setObjectName("cluster_new_files")
        self.verticalLayout.addWidget(self.cluster_new_files)
        self.ignore_file_mbids = QtWidgets.QCheckBox(parent=self.general_box)
        self.ignore_file_mbids.setObjectName("ignore_file_mbids")
        self.verticalLayout.addWidget(self.ignore_file_mbids)
        self.vboxlayout.addWidget(self.general_box)
        self.submission_box = QtWidgets.QGroupBox(parent=GeneralOptionsPage)
        self.submission_box.setObjectName("submission_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.submission_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.submit_isrcs = QtWidgets.QCheckBox(parent=self.submission_box)
        self.submit_isrcs.setObjectName("submit_isrcs")
        self.verticalLayout_2.addWidget(self.submit_isrcs)
        self.vboxlayout.addWidget(self.submission_box)
        spacerItem2 = QtWidgets.QSpacerItem(181, 21, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vboxlayout.addItem(spacerItem2)

        self.retranslateUi(GeneralOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(GeneralOptionsPage)
        GeneralOptionsPage.setTabOrder(self.server_host, self.server_port)
        GeneralOptionsPage.setTabOrder(self.server_port, self.use_server_for_submission)
        GeneralOptionsPage.setTabOrder(self.use_server_for_submission, self.login)
        GeneralOptionsPage.setTabOrder(self.login, self.logout)
        GeneralOptionsPage.setTabOrder(self.logout, self.enable_user_collections)
        GeneralOptionsPage.setTabOrder(self.enable_user_collections, self.analyze_new_files)
        GeneralOptionsPage.setTabOrder(self.analyze_new_files, self.cluster_new_files)
        GeneralOptionsPage.setTabOrder(self.cluster_new_files, self.ignore_file_mbids)
        GeneralOptionsPage.setTabOrder(self.ignore_file_mbids, self.submit_isrcs)

    def retranslateUi(self, GeneralOptionsPage):
        self.musicbrainz_server_box.setTitle(_("MusicBrainz Server"))
        self.label.setText(_("Server address:"))
        self.label_4.setText(_("You have configured an unofficial MusicBrainz server. By default submissions of releases, recordings and disc IDs will go to the primary database on musicbrainz.org."))
        self.use_server_for_submission.setText(_("Submit data to the configured server"))
        self.label_7.setText(_("Port:"))
        self.musicbrainz_account_box.setTitle(_("MusicBrainz Account"))
        self.login.setText(_("Log in"))
        self.logout.setText(_("Log out"))
        self.enable_user_collections.setText(_("Enable managing user collections"))
        self.general_box.setTitle(_("General"))
        self.analyze_new_files.setText(_("Automatically scan all new files"))
        self.cluster_new_files.setText(_("Automatically cluster all new files"))
        self.ignore_file_mbids.setText(_("Ignore MBIDs when loading new files"))
        self.submission_box.setTitle(_("Submission"))
        self.submit_isrcs.setToolTip(_("When enabled, ISRCs found in files that are not yet associated with the matched recording in MusicBrainz can be submitted."))
        self.submit_isrcs.setText(_("Submit ISRCs to MusicBrainz when tagging"))
