# Form implementation generated from reading ui file 'ui/options_maintenance.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# Automatically generated - do not edit.
# Use `python setup.py build_ui` to update it.

from PyQt6 import (
    QtCore,
    QtGui,
    QtWidgets,
)

from picard.i18n import gettext as _


class Ui_MaintenanceOptionsPage(object):
    def setupUi(self, MaintenanceOptionsPage):
        MaintenanceOptionsPage.setObjectName("MaintenanceOptionsPage")
        MaintenanceOptionsPage.resize(334, 397)
        self.vboxlayout = QtWidgets.QVBoxLayout(MaintenanceOptionsPage)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(parent=MaintenanceOptionsPage)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.config_file = QtWidgets.QLineEdit(parent=MaintenanceOptionsPage)
        self.config_file.setReadOnly(True)
        self.config_file.setObjectName("config_file")
        self.horizontalLayout_3.addWidget(self.config_file)
        self.open_folder_button = QtWidgets.QToolButton(parent=MaintenanceOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_folder_button.sizePolicy().hasHeightForWidth())
        self.open_folder_button.setSizePolicy(sizePolicy)
        self.open_folder_button.setObjectName("open_folder_button")
        self.horizontalLayout_3.addWidget(self.open_folder_button)
        self.vboxlayout.addLayout(self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(parent=MaintenanceOptionsPage)
        self.label_2.setObjectName("label_2")
        self.vboxlayout.addWidget(self.label_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.autobackup_dir = QtWidgets.QLineEdit(parent=MaintenanceOptionsPage)
        self.autobackup_dir.setObjectName("autobackup_dir")
        self.horizontalLayout_6.addWidget(self.autobackup_dir)
        self.browse_autobackup_dir = QtWidgets.QToolButton(parent=MaintenanceOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_autobackup_dir.sizePolicy().hasHeightForWidth())
        self.browse_autobackup_dir.setSizePolicy(sizePolicy)
        self.browse_autobackup_dir.setObjectName("browse_autobackup_dir")
        self.horizontalLayout_6.addWidget(self.browse_autobackup_dir)
        self.vboxlayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.load_backup_button = QtWidgets.QToolButton(parent=MaintenanceOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_backup_button.sizePolicy().hasHeightForWidth())
        self.load_backup_button.setSizePolicy(sizePolicy)
        self.load_backup_button.setObjectName("load_backup_button")
        self.horizontalLayout.addWidget(self.load_backup_button)
        self.save_backup_button = QtWidgets.QToolButton(parent=MaintenanceOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_backup_button.sizePolicy().hasHeightForWidth())
        self.save_backup_button.setSizePolicy(sizePolicy)
        self.save_backup_button.setObjectName("save_backup_button")
        self.horizontalLayout.addWidget(self.save_backup_button)
        self.vboxlayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(parent=MaintenanceOptionsPage)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.vboxlayout.addWidget(self.line_2)
        self.option_counts = QtWidgets.QLabel(parent=MaintenanceOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_counts.sizePolicy().hasHeightForWidth())
        self.option_counts.setSizePolicy(sizePolicy)
        self.option_counts.setText("")
        self.option_counts.setObjectName("option_counts")
        self.vboxlayout.addWidget(self.option_counts)
        self.description = QtWidgets.QLabel(parent=MaintenanceOptionsPage)
        self.description.setText("")
        self.description.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.description.setWordWrap(True)
        self.description.setIndent(0)
        self.description.setObjectName("description")
        self.vboxlayout.addWidget(self.description)
        spacerItem1 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.vboxlayout.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(parent=MaintenanceOptionsPage)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.vboxlayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.select_all = QtWidgets.QCheckBox(parent=MaintenanceOptionsPage)
        self.select_all.setObjectName("select_all")
        self.horizontalLayout_2.addWidget(self.select_all)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.enable_cleanup = QtWidgets.QCheckBox(parent=MaintenanceOptionsPage)
        self.enable_cleanup.setObjectName("enable_cleanup")
        self.horizontalLayout_2.addWidget(self.enable_cleanup)
        self.vboxlayout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(parent=MaintenanceOptionsPage)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.vboxlayout.addWidget(self.tableWidget)

        self.retranslateUi(MaintenanceOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(MaintenanceOptionsPage)
        MaintenanceOptionsPage.setTabOrder(self.config_file, self.open_folder_button)
        MaintenanceOptionsPage.setTabOrder(self.open_folder_button, self.autobackup_dir)
        MaintenanceOptionsPage.setTabOrder(self.autobackup_dir, self.browse_autobackup_dir)
        MaintenanceOptionsPage.setTabOrder(self.browse_autobackup_dir, self.load_backup_button)
        MaintenanceOptionsPage.setTabOrder(self.load_backup_button, self.save_backup_button)
        MaintenanceOptionsPage.setTabOrder(self.save_backup_button, self.select_all)
        MaintenanceOptionsPage.setTabOrder(self.select_all, self.enable_cleanup)
        MaintenanceOptionsPage.setTabOrder(self.enable_cleanup, self.tableWidget)

    def retranslateUi(self, MaintenanceOptionsPage):
        self.label.setText(_("Configuration file:"))
        self.open_folder_button.setText(_("Open folder…"))
        self.label_2.setText(_("Automatic configuration backups directory:"))
        self.browse_autobackup_dir.setText(_("Browse…"))
        self.load_backup_button.setText(_("Load backup…"))
        self.save_backup_button.setText(_("Save backup…"))
        self.select_all.setText(_("Select all"))
        self.enable_cleanup.setText(_("Remove selected options"))
