# -*- coding: utf-8 -*-
# Automatically generated - don't edit.
# Use the "country_sql2py.py" script in the "scripts" folder and overwrite this
# file with the generated "countries.py" to update it.

from gettext import dgettext

RELEASE_COUNTRIES = {
    u"AF": dgettext("picard-countries", u"Afghanistan"),
    u"AL": dgettext("picard-countries", u"Albania"),
    u"DZ": dgettext("picard-countries", u"Algeria"),
    u"AS": dgettext("picard-countries", u"American Samoa"),
    u"AD": dgettext("picard-countries", u"Andorra"),
    u"AO": dgettext("picard-countries", u"Angola"),
    u"AI": dgettext("picard-countries", u"Anguilla"),
    u"AQ": dgettext("picard-countries", u"Antarctica"),
    u"AG": dgettext("picard-countries", u"Antigua and Barbuda"),
    u"AR": dgettext("picard-countries", u"Argentina"),
    u"AM": dgettext("picard-countries", u"Armenia"),
    u"AW": dgettext("picard-countries", u"Aruba"),
    u"AU": dgettext("picard-countries", u"Australia"),
    u"AT": dgettext("picard-countries", u"Austria"),
    u"AZ": dgettext("picard-countries", u"Azerbaijan"),
    u"BS": dgettext("picard-countries", u"Bahamas"),
    u"BH": dgettext("picard-countries", u"Bahrain"),
    u"BD": dgettext("picard-countries", u"Bangladesh"),
    u"BB": dgettext("picard-countries", u"Barbados"),
    u"BY": dgettext("picard-countries", u"Belarus"),
    u"BE": dgettext("picard-countries", u"Belgium"),
    u"BZ": dgettext("picard-countries", u"Belize"),
    u"BJ": dgettext("picard-countries", u"Benin"),
    u"BM": dgettext("picard-countries", u"Bermuda"),
    u"BT": dgettext("picard-countries", u"Bhutan"),
    u"HR": dgettext("picard-countries", u"Croatia"),
    u"BW": dgettext("picard-countries", u"Botswana"),
    u"BV": dgettext("picard-countries", u"Bouvet Island"),
    u"BR": dgettext("picard-countries", u"Brazil"),
    u"IO": dgettext("picard-countries", u"British Indian Ocean Territory"),
    u"BN": dgettext("picard-countries", u"Brunei Darussalam"),
    u"BG": dgettext("picard-countries", u"Bulgaria"),
    u"BF": dgettext("picard-countries", u"Burkina Faso"),
    u"BI": dgettext("picard-countries", u"Burundi"),
    u"KH": dgettext("picard-countries", u"Cambodia"),
    u"CM": dgettext("picard-countries", u"Cameroon"),
    u"CA": dgettext("picard-countries", u"Canada"),
    u"CV": dgettext("picard-countries", u"Cape Verde"),
    u"KY": dgettext("picard-countries", u"Cayman Islands"),
    u"CF": dgettext("picard-countries", u"Central African Republic"),
    u"TD": dgettext("picard-countries", u"Chad"),
    u"CL": dgettext("picard-countries", u"Chile"),
    u"CN": dgettext("picard-countries", u"China"),
    u"CX": dgettext("picard-countries", u"Christmas Island"),
    u"CC": dgettext("picard-countries", u"Cocos (Keeling) Islands"),
    u"CO": dgettext("picard-countries", u"Colombia"),
    u"KM": dgettext("picard-countries", u"Comoros"),
    u"CG": dgettext("picard-countries", u"Congo"),
    u"CK": dgettext("picard-countries", u"Cook Islands"),
    u"CR": dgettext("picard-countries", u"Costa Rica"),
    u"VG": dgettext("picard-countries", u"Virgin Islands, British"),
    u"CU": dgettext("picard-countries", u"Cuba"),
    u"CY": dgettext("picard-countries", u"Cyprus"),
    u"CZ": dgettext("picard-countries", u"Czech Republic"),
    u"DK": dgettext("picard-countries", u"Denmark"),
    u"DJ": dgettext("picard-countries", u"Djibouti"),
    u"DM": dgettext("picard-countries", u"Dominica"),
    u"DO": dgettext("picard-countries", u"Dominican Republic"),
    u"EC": dgettext("picard-countries", u"Ecuador"),
    u"EG": dgettext("picard-countries", u"Egypt"),
    u"SV": dgettext("picard-countries", u"El Salvador"),
    u"GQ": dgettext("picard-countries", u"Equatorial Guinea"),
    u"ER": dgettext("picard-countries", u"Eritrea"),
    u"EE": dgettext("picard-countries", u"Estonia"),
    u"ET": dgettext("picard-countries", u"Ethiopia"),
    u"FK": dgettext("picard-countries", u"Falkland Islands (Malvinas)"),
    u"FO": dgettext("picard-countries", u"Faroe Islands"),
    u"FJ": dgettext("picard-countries", u"Fiji"),
    u"FI": dgettext("picard-countries", u"Finland"),
    u"FR": dgettext("picard-countries", u"France"),
    u"GF": dgettext("picard-countries", u"French Guiana"),
    u"PF": dgettext("picard-countries", u"French Polynesia"),
    u"TF": dgettext("picard-countries", u"French Southern Territories"),
    u"GA": dgettext("picard-countries", u"Gabon"),
    u"GM": dgettext("picard-countries", u"Gambia"),
    u"GE": dgettext("picard-countries", u"Georgia"),
    u"DE": dgettext("picard-countries", u"Germany"),
    u"GH": dgettext("picard-countries", u"Ghana"),
    u"GI": dgettext("picard-countries", u"Gibraltar"),
    u"GR": dgettext("picard-countries", u"Greece"),
    u"GL": dgettext("picard-countries", u"Greenland"),
    u"GD": dgettext("picard-countries", u"Grenada"),
    u"GP": dgettext("picard-countries", u"Guadeloupe"),
    u"GU": dgettext("picard-countries", u"Guam"),
    u"GT": dgettext("picard-countries", u"Guatemala"),
    u"GN": dgettext("picard-countries", u"Guinea"),
    u"GW": dgettext("picard-countries", u"Guinea-Bissau"),
    u"GY": dgettext("picard-countries", u"Guyana"),
    u"HT": dgettext("picard-countries", u"Haiti"),
    u"VI": dgettext("picard-countries", u"Virgin Islands, U.S."),
    u"HN": dgettext("picard-countries", u"Honduras"),
    u"HK": dgettext("picard-countries", u"Hong Kong"),
    u"HU": dgettext("picard-countries", u"Hungary"),
    u"IS": dgettext("picard-countries", u"Iceland"),
    u"IN": dgettext("picard-countries", u"India"),
    u"ID": dgettext("picard-countries", u"Indonesia"),
    u"WF": dgettext("picard-countries", u"Wallis and Futuna"),
    u"IQ": dgettext("picard-countries", u"Iraq"),
    u"IE": dgettext("picard-countries", u"Ireland"),
    u"IL": dgettext("picard-countries", u"Israel"),
    u"IT": dgettext("picard-countries", u"Italy"),
    u"JM": dgettext("picard-countries", u"Jamaica"),
    u"JP": dgettext("picard-countries", u"Japan"),
    u"JO": dgettext("picard-countries", u"Jordan"),
    u"KZ": dgettext("picard-countries", u"Kazakhstan"),
    u"KE": dgettext("picard-countries", u"Kenya"),
    u"KI": dgettext("picard-countries", u"Kiribati"),
    u"KW": dgettext("picard-countries", u"Kuwait"),
    u"KG": dgettext("picard-countries", u"Kyrgyzstan"),
    u"LA": dgettext("picard-countries", u"Lao People's Democratic Republic"),
    u"LV": dgettext("picard-countries", u"Latvia"),
    u"LB": dgettext("picard-countries", u"Lebanon"),
    u"LS": dgettext("picard-countries", u"Lesotho"),
    u"LR": dgettext("picard-countries", u"Liberia"),
    u"LI": dgettext("picard-countries", u"Liechtenstein"),
    u"LT": dgettext("picard-countries", u"Lithuania"),
    u"LU": dgettext("picard-countries", u"Luxembourg"),
    u"MS": dgettext("picard-countries", u"Montserrat"),
    u"MK": dgettext("picard-countries", u"Macedonia, The Former Yugoslav Republic of"),
    u"MG": dgettext("picard-countries", u"Madagascar"),
    u"MW": dgettext("picard-countries", u"Malawi"),
    u"MY": dgettext("picard-countries", u"Malaysia"),
    u"MV": dgettext("picard-countries", u"Maldives"),
    u"ML": dgettext("picard-countries", u"Mali"),
    u"MT": dgettext("picard-countries", u"Malta"),
    u"MH": dgettext("picard-countries", u"Marshall Islands"),
    u"MQ": dgettext("picard-countries", u"Martinique"),
    u"MR": dgettext("picard-countries", u"Mauritania"),
    u"MU": dgettext("picard-countries", u"Mauritius"),
    u"YT": dgettext("picard-countries", u"Mayotte"),
    u"MX": dgettext("picard-countries", u"Mexico"),
    u"FM": dgettext("picard-countries", u"Micronesia, Federated States of"),
    u"MA": dgettext("picard-countries", u"Morocco"),
    u"MC": dgettext("picard-countries", u"Monaco"),
    u"MN": dgettext("picard-countries", u"Mongolia"),
    u"MZ": dgettext("picard-countries", u"Mozambique"),
    u"MM": dgettext("picard-countries", u"Myanmar"),
    u"NA": dgettext("picard-countries", u"Namibia"),
    u"NR": dgettext("picard-countries", u"Nauru"),
    u"NP": dgettext("picard-countries", u"Nepal"),
    u"NL": dgettext("picard-countries", u"Netherlands"),
    u"NC": dgettext("picard-countries", u"New Caledonia"),
    u"NZ": dgettext("picard-countries", u"New Zealand"),
    u"NI": dgettext("picard-countries", u"Nicaragua"),
    u"NE": dgettext("picard-countries", u"Niger"),
    u"NG": dgettext("picard-countries", u"Nigeria"),
    u"NU": dgettext("picard-countries", u"Niue"),
    u"NF": dgettext("picard-countries", u"Norfolk Island"),
    u"MP": dgettext("picard-countries", u"Northern Mariana Islands"),
    u"NO": dgettext("picard-countries", u"Norway"),
    u"OM": dgettext("picard-countries", u"Oman"),
    u"PK": dgettext("picard-countries", u"Pakistan"),
    u"PW": dgettext("picard-countries", u"Palau"),
    u"PA": dgettext("picard-countries", u"Panama"),
    u"PG": dgettext("picard-countries", u"Papua New Guinea"),
    u"PY": dgettext("picard-countries", u"Paraguay"),
    u"PE": dgettext("picard-countries", u"Peru"),
    u"PH": dgettext("picard-countries", u"Philippines"),
    u"PN": dgettext("picard-countries", u"Pitcairn"),
    u"PL": dgettext("picard-countries", u"Poland"),
    u"PT": dgettext("picard-countries", u"Portugal"),
    u"PR": dgettext("picard-countries", u"Puerto Rico"),
    u"QA": dgettext("picard-countries", u"Qatar"),
    u"RO": dgettext("picard-countries", u"Romania"),
    u"LY": dgettext("picard-countries", u"Libya"),
    u"RU": dgettext("picard-countries", u"Russian Federation"),
    u"RW": dgettext("picard-countries", u"Rwanda"),
    u"KN": dgettext("picard-countries", u"Saint Kitts and Nevis"),
    u"LC": dgettext("picard-countries", u"Saint Lucia"),
    u"VC": dgettext("picard-countries", u"Saint Vincent and The Grenadines"),
    u"WS": dgettext("picard-countries", u"Samoa"),
    u"SM": dgettext("picard-countries", u"San Marino"),
    u"ST": dgettext("picard-countries", u"Sao Tome and Principe"),
    u"SA": dgettext("picard-countries", u"Saudi Arabia"),
    u"SN": dgettext("picard-countries", u"Senegal"),
    u"SC": dgettext("picard-countries", u"Seychelles"),
    u"SL": dgettext("picard-countries", u"Sierra Leone"),
    u"SG": dgettext("picard-countries", u"Singapore"),
    u"SI": dgettext("picard-countries", u"Slovenia"),
    u"SB": dgettext("picard-countries", u"Solomon Islands"),
    u"SO": dgettext("picard-countries", u"Somalia"),
    u"ZA": dgettext("picard-countries", u"South Africa"),
    u"ES": dgettext("picard-countries", u"Spain"),
    u"LK": dgettext("picard-countries", u"Sri Lanka"),
    u"SD": dgettext("picard-countries", u"Sudan"),
    u"SR": dgettext("picard-countries", u"Suriname"),
    u"SZ": dgettext("picard-countries", u"Swaziland"),
    u"SE": dgettext("picard-countries", u"Sweden"),
    u"CH": dgettext("picard-countries", u"Switzerland"),
    u"SY": dgettext("picard-countries", u"Syrian Arab Republic"),
    u"TJ": dgettext("picard-countries", u"Tajikistan"),
    u"TZ": dgettext("picard-countries", u"Tanzania, United Republic of"),
    u"TH": dgettext("picard-countries", u"Thailand"),
    u"TG": dgettext("picard-countries", u"Togo"),
    u"TK": dgettext("picard-countries", u"Tokelau"),
    u"TO": dgettext("picard-countries", u"Tonga"),
    u"TT": dgettext("picard-countries", u"Trinidad and Tobago"),
    u"TN": dgettext("picard-countries", u"Tunisia"),
    u"TR": dgettext("picard-countries", u"Turkey"),
    u"TM": dgettext("picard-countries", u"Turkmenistan"),
    u"TC": dgettext("picard-countries", u"Turks and Caicos Islands"),
    u"TV": dgettext("picard-countries", u"Tuvalu"),
    u"UG": dgettext("picard-countries", u"Uganda"),
    u"UA": dgettext("picard-countries", u"Ukraine"),
    u"AE": dgettext("picard-countries", u"United Arab Emirates"),
    u"GB": dgettext("picard-countries", u"United Kingdom"),
    u"US": dgettext("picard-countries", u"United States"),
    u"UM": dgettext("picard-countries", u"United States Minor Outlying Islands"),
    u"UY": dgettext("picard-countries", u"Uruguay"),
    u"UZ": dgettext("picard-countries", u"Uzbekistan"),
    u"VU": dgettext("picard-countries", u"Vanuatu"),
    u"VA": dgettext("picard-countries", u"Vatican City State (Holy See)"),
    u"VN": dgettext("picard-countries", u"Viet Nam"),
    u"EH": dgettext("picard-countries", u"Western Sahara"),
    u"YE": dgettext("picard-countries", u"Yemen"),
    u"ZM": dgettext("picard-countries", u"Zambia"),
    u"ZW": dgettext("picard-countries", u"Zimbabwe"),
    u"TW": dgettext("picard-countries", u"Taiwan"),
    u"XW": dgettext("picard-countries", u"[Worldwide]"),
    u"XE": dgettext("picard-countries", u"Europe"),
    u"SU": dgettext("picard-countries", u"Soviet Union (historical, 1922-1991)"),
    u"XG": dgettext("picard-countries", u"East Germany (historical, 1949-1990)"),
    u"XC": dgettext("picard-countries", u"Czechoslovakia (historical, 1918-1992)"),
    u"CD": dgettext("picard-countries", u"Congo, The Democratic Republic of the"),
    u"SK": dgettext("picard-countries", u"Slovakia"),
    u"BA": dgettext("picard-countries", u"Bosnia and Herzegovina"),
    u"KP": dgettext("picard-countries", u"Korea (North), Democratic People's Republic of"),
    u"KR": dgettext("picard-countries", u"Korea (South), Republic of"),
    u"ME": dgettext("picard-countries", u"Montenegro"),
    u"GS": dgettext("picard-countries", u"South Georgia and the South Sandwich Islands"),
    u"PS": dgettext("picard-countries", u"Palestinian Territory"),
    u"MO": dgettext("picard-countries", u"Macao"),
    u"TL": dgettext("picard-countries", u"Timor-Leste"),
    u"AX": dgettext("picard-countries", u"Åland Islands"),
    u"GG": dgettext("picard-countries", u"Guernsey"),
    u"IM": dgettext("picard-countries", u"Isle of Man"),
    u"JE": dgettext("picard-countries", u"Jersey"),
    u"RS": dgettext("picard-countries", u"Serbia"),
    u"BL": dgettext("picard-countries", u"Saint Barthélemy"),
    u"YU": dgettext("picard-countries", u"Yugoslavia (historical, 1918-2003)"),
    u"CS": dgettext("picard-countries", u"Serbia and Montenegro (historical, 2003-2006)"),
    u"CI": dgettext("picard-countries", u"Côte d'Ivoire"),
    u"HM": dgettext("picard-countries", u"Heard Island and McDonald Islands"),
    u"IR": dgettext("picard-countries", u"Iran, Islamic Republic of"),
    u"PM": dgettext("picard-countries", u"Saint Pierre and Miquelon"),
    u"SJ": dgettext("picard-countries", u"Svalbard and Jan Mayen"),
    u"SS": dgettext("picard-countries", u"South Sudan"),
    u"BQ": dgettext("picard-countries", u"Bonaire, Sint Eustatius and Saba"),
    u"CW": dgettext("picard-countries", u"Curaçao"),
    u"SX": dgettext("picard-countries", u"Sint Maarten (Dutch part)"),
    u"AN": dgettext("picard-countries", u"Netherlands Antilles (historical, 1954-2010)"),
    u"SH": dgettext("picard-countries", u"Saint Helena, Ascension and Tristan da Cunha"),
    u"BO": dgettext("picard-countries", u"Bolivia, Plurinational State of"),
    u"VE": dgettext("picard-countries", u"Venezuela, Bolivarian Republic of"),
    u"MD": dgettext("picard-countries", u"Moldova, Republic of"),
    u"RE": dgettext("picard-countries", u"Réunion"),
    u"MF": dgettext("picard-countries", u"Saint Martin (French part)"),
}