# -*- coding: utf-8 -*-
# Automatically generated - don't edit.
# Use the "country_sql2py.py" script in the "scripts" folder and overwrite this
# file with the generated "countries.py" to update it.

from gettext import dgettext

RELEASE_COUNTRIES = {
    u"AF": dgettext("picard-countries", "Afghanistan"),
    u"AL": dgettext("picard-countries", "Albania"),
    u"DZ": dgettext("picard-countries", "Algeria"),
    u"AS": dgettext("picard-countries", "American Samoa"),
    u"AD": dgettext("picard-countries", "Andorra"),
    u"AO": dgettext("picard-countries", "Angola"),
    u"AI": dgettext("picard-countries", "Anguilla"),
    u"AQ": dgettext("picard-countries", "Antarctica"),
    u"AG": dgettext("picard-countries", "Antigua and Barbuda"),
    u"AR": dgettext("picard-countries", "Argentina"),
    u"AM": dgettext("picard-countries", "Armenia"),
    u"AW": dgettext("picard-countries", "Aruba"),
    u"AU": dgettext("picard-countries", "Australia"),
    u"AT": dgettext("picard-countries", "Austria"),
    u"AZ": dgettext("picard-countries", "Azerbaijan"),
    u"BS": dgettext("picard-countries", "Bahamas"),
    u"BH": dgettext("picard-countries", "Bahrain"),
    u"BD": dgettext("picard-countries", "Bangladesh"),
    u"BB": dgettext("picard-countries", "Barbados"),
    u"BY": dgettext("picard-countries", "Belarus"),
    u"BE": dgettext("picard-countries", "Belgium"),
    u"BZ": dgettext("picard-countries", "Belize"),
    u"BJ": dgettext("picard-countries", "Benin"),
    u"BM": dgettext("picard-countries", "Bermuda"),
    u"BT": dgettext("picard-countries", "Bhutan"),
    u"HR": dgettext("picard-countries", "Croatia"),
    u"BW": dgettext("picard-countries", "Botswana"),
    u"BV": dgettext("picard-countries", "Bouvet Island"),
    u"BR": dgettext("picard-countries", "Brazil"),
    u"IO": dgettext("picard-countries", "British Indian Ocean Territory"),
    u"BN": dgettext("picard-countries", "Brunei Darussalam"),
    u"BG": dgettext("picard-countries", "Bulgaria"),
    u"BF": dgettext("picard-countries", "Burkina Faso"),
    u"BI": dgettext("picard-countries", "Burundi"),
    u"KH": dgettext("picard-countries", "Cambodia"),
    u"CM": dgettext("picard-countries", "Cameroon"),
    u"CA": dgettext("picard-countries", "Canada"),
    u"CV": dgettext("picard-countries", "Cape Verde"),
    u"KY": dgettext("picard-countries", "Cayman Islands"),
    u"CF": dgettext("picard-countries", "Central African Republic"),
    u"TD": dgettext("picard-countries", "Chad"),
    u"CL": dgettext("picard-countries", "Chile"),
    u"CN": dgettext("picard-countries", "China"),
    u"CX": dgettext("picard-countries", "Christmas Island"),
    u"CC": dgettext("picard-countries", "Cocos (Keeling) Islands"),
    u"CO": dgettext("picard-countries", "Colombia"),
    u"KM": dgettext("picard-countries", "Comoros"),
    u"CG": dgettext("picard-countries", "Congo"),
    u"CK": dgettext("picard-countries", "Cook Islands"),
    u"CR": dgettext("picard-countries", "Costa Rica"),
    u"VG": dgettext("picard-countries", "Virgin Islands, British"),
    u"CU": dgettext("picard-countries", "Cuba"),
    u"CY": dgettext("picard-countries", "Cyprus"),
    u"CZ": dgettext("picard-countries", "Czech Republic"),
    u"DK": dgettext("picard-countries", "Denmark"),
    u"DJ": dgettext("picard-countries", "Djibouti"),
    u"DM": dgettext("picard-countries", "Dominica"),
    u"DO": dgettext("picard-countries", "Dominican Republic"),
    u"EC": dgettext("picard-countries", "Ecuador"),
    u"EG": dgettext("picard-countries", "Egypt"),
    u"SV": dgettext("picard-countries", "El Salvador"),
    u"GQ": dgettext("picard-countries", "Equatorial Guinea"),
    u"ER": dgettext("picard-countries", "Eritrea"),
    u"EE": dgettext("picard-countries", "Estonia"),
    u"ET": dgettext("picard-countries", "Ethiopia"),
    u"FK": dgettext("picard-countries", "Falkland Islands (Malvinas)"),
    u"FO": dgettext("picard-countries", "Faroe Islands"),
    u"FJ": dgettext("picard-countries", "Fiji"),
    u"FI": dgettext("picard-countries", "Finland"),
    u"FR": dgettext("picard-countries", "France"),
    u"GF": dgettext("picard-countries", "French Guiana"),
    u"PF": dgettext("picard-countries", "French Polynesia"),
    u"TF": dgettext("picard-countries", "French Southern Territories"),
    u"GA": dgettext("picard-countries", "Gabon"),
    u"GM": dgettext("picard-countries", "Gambia"),
    u"GE": dgettext("picard-countries", "Georgia"),
    u"DE": dgettext("picard-countries", "Germany"),
    u"GH": dgettext("picard-countries", "Ghana"),
    u"GI": dgettext("picard-countries", "Gibraltar"),
    u"GR": dgettext("picard-countries", "Greece"),
    u"GL": dgettext("picard-countries", "Greenland"),
    u"GD": dgettext("picard-countries", "Grenada"),
    u"GP": dgettext("picard-countries", "Guadeloupe"),
    u"GU": dgettext("picard-countries", "Guam"),
    u"GT": dgettext("picard-countries", "Guatemala"),
    u"GN": dgettext("picard-countries", "Guinea"),
    u"GW": dgettext("picard-countries", "Guinea-Bissau"),
    u"GY": dgettext("picard-countries", "Guyana"),
    u"HT": dgettext("picard-countries", "Haiti"),
    u"VI": dgettext("picard-countries", "Virgin Islands, U.S."),
    u"HN": dgettext("picard-countries", "Honduras"),
    u"HK": dgettext("picard-countries", "Hong Kong"),
    u"HU": dgettext("picard-countries", "Hungary"),
    u"IS": dgettext("picard-countries", "Iceland"),
    u"IN": dgettext("picard-countries", "India"),
    u"ID": dgettext("picard-countries", "Indonesia"),
    u"WF": dgettext("picard-countries", "Wallis and Futuna"),
    u"IQ": dgettext("picard-countries", "Iraq"),
    u"IE": dgettext("picard-countries", "Ireland"),
    u"IL": dgettext("picard-countries", "Israel"),
    u"IT": dgettext("picard-countries", "Italy"),
    u"JM": dgettext("picard-countries", "Jamaica"),
    u"JP": dgettext("picard-countries", "Japan"),
    u"JO": dgettext("picard-countries", "Jordan"),
    u"KZ": dgettext("picard-countries", "Kazakhstan"),
    u"KE": dgettext("picard-countries", "Kenya"),
    u"KI": dgettext("picard-countries", "Kiribati"),
    u"KW": dgettext("picard-countries", "Kuwait"),
    u"KG": dgettext("picard-countries", "Kyrgyzstan"),
    u"LA": dgettext("picard-countries", "Lao People's Democratic Republic"),
    u"LV": dgettext("picard-countries", "Latvia"),
    u"LB": dgettext("picard-countries", "Lebanon"),
    u"LS": dgettext("picard-countries", "Lesotho"),
    u"LR": dgettext("picard-countries", "Liberia"),
    u"LI": dgettext("picard-countries", "Liechtenstein"),
    u"LT": dgettext("picard-countries", "Lithuania"),
    u"LU": dgettext("picard-countries", "Luxembourg"),
    u"MS": dgettext("picard-countries", "Montserrat"),
    u"MK": dgettext("picard-countries", "Macedonia, The Former Yugoslav Republic of"),
    u"MG": dgettext("picard-countries", "Madagascar"),
    u"MW": dgettext("picard-countries", "Malawi"),
    u"MY": dgettext("picard-countries", "Malaysia"),
    u"MV": dgettext("picard-countries", "Maldives"),
    u"ML": dgettext("picard-countries", "Mali"),
    u"MT": dgettext("picard-countries", "Malta"),
    u"MH": dgettext("picard-countries", "Marshall Islands"),
    u"MQ": dgettext("picard-countries", "Martinique"),
    u"MR": dgettext("picard-countries", "Mauritania"),
    u"MU": dgettext("picard-countries", "Mauritius"),
    u"YT": dgettext("picard-countries", "Mayotte"),
    u"MX": dgettext("picard-countries", "Mexico"),
    u"FM": dgettext("picard-countries", "Micronesia, Federated States of"),
    u"MA": dgettext("picard-countries", "Morocco"),
    u"MC": dgettext("picard-countries", "Monaco"),
    u"MN": dgettext("picard-countries", "Mongolia"),
    u"MZ": dgettext("picard-countries", "Mozambique"),
    u"MM": dgettext("picard-countries", "Myanmar"),
    u"NA": dgettext("picard-countries", "Namibia"),
    u"NR": dgettext("picard-countries", "Nauru"),
    u"NP": dgettext("picard-countries", "Nepal"),
    u"NL": dgettext("picard-countries", "Netherlands"),
    u"NC": dgettext("picard-countries", "New Caledonia"),
    u"NZ": dgettext("picard-countries", "New Zealand"),
    u"NI": dgettext("picard-countries", "Nicaragua"),
    u"NE": dgettext("picard-countries", "Niger"),
    u"NG": dgettext("picard-countries", "Nigeria"),
    u"NU": dgettext("picard-countries", "Niue"),
    u"NF": dgettext("picard-countries", "Norfolk Island"),
    u"MP": dgettext("picard-countries", "Northern Mariana Islands"),
    u"NO": dgettext("picard-countries", "Norway"),
    u"OM": dgettext("picard-countries", "Oman"),
    u"PK": dgettext("picard-countries", "Pakistan"),
    u"PW": dgettext("picard-countries", "Palau"),
    u"PA": dgettext("picard-countries", "Panama"),
    u"PG": dgettext("picard-countries", "Papua New Guinea"),
    u"PY": dgettext("picard-countries", "Paraguay"),
    u"PE": dgettext("picard-countries", "Peru"),
    u"PH": dgettext("picard-countries", "Philippines"),
    u"PN": dgettext("picard-countries", "Pitcairn"),
    u"PL": dgettext("picard-countries", "Poland"),
    u"PT": dgettext("picard-countries", "Portugal"),
    u"PR": dgettext("picard-countries", "Puerto Rico"),
    u"QA": dgettext("picard-countries", "Qatar"),
    u"RO": dgettext("picard-countries", "Romania"),
    u"LY": dgettext("picard-countries", "Libya"),
    u"RU": dgettext("picard-countries", "Russian Federation"),
    u"RW": dgettext("picard-countries", "Rwanda"),
    u"KN": dgettext("picard-countries", "Saint Kitts and Nevis"),
    u"LC": dgettext("picard-countries", "Saint Lucia"),
    u"VC": dgettext("picard-countries", "Saint Vincent and The Grenadines"),
    u"WS": dgettext("picard-countries", "Samoa"),
    u"SM": dgettext("picard-countries", "San Marino"),
    u"ST": dgettext("picard-countries", "Sao Tome and Principe"),
    u"SA": dgettext("picard-countries", "Saudi Arabia"),
    u"SN": dgettext("picard-countries", "Senegal"),
    u"SC": dgettext("picard-countries", "Seychelles"),
    u"SL": dgettext("picard-countries", "Sierra Leone"),
    u"SG": dgettext("picard-countries", "Singapore"),
    u"SI": dgettext("picard-countries", "Slovenia"),
    u"SB": dgettext("picard-countries", "Solomon Islands"),
    u"SO": dgettext("picard-countries", "Somalia"),
    u"ZA": dgettext("picard-countries", "South Africa"),
    u"ES": dgettext("picard-countries", "Spain"),
    u"LK": dgettext("picard-countries", "Sri Lanka"),
    u"SD": dgettext("picard-countries", "Sudan"),
    u"SR": dgettext("picard-countries", "Suriname"),
    u"SZ": dgettext("picard-countries", "Swaziland"),
    u"SE": dgettext("picard-countries", "Sweden"),
    u"CH": dgettext("picard-countries", "Switzerland"),
    u"SY": dgettext("picard-countries", "Syrian Arab Republic"),
    u"TJ": dgettext("picard-countries", "Tajikistan"),
    u"TZ": dgettext("picard-countries", "Tanzania, United Republic of"),
    u"TH": dgettext("picard-countries", "Thailand"),
    u"TG": dgettext("picard-countries", "Togo"),
    u"TK": dgettext("picard-countries", "Tokelau"),
    u"TO": dgettext("picard-countries", "Tonga"),
    u"TT": dgettext("picard-countries", "Trinidad and Tobago"),
    u"TN": dgettext("picard-countries", "Tunisia"),
    u"TR": dgettext("picard-countries", "Turkey"),
    u"TM": dgettext("picard-countries", "Turkmenistan"),
    u"TC": dgettext("picard-countries", "Turks and Caicos Islands"),
    u"TV": dgettext("picard-countries", "Tuvalu"),
    u"UG": dgettext("picard-countries", "Uganda"),
    u"UA": dgettext("picard-countries", "Ukraine"),
    u"AE": dgettext("picard-countries", "United Arab Emirates"),
    u"GB": dgettext("picard-countries", "United Kingdom"),
    u"US": dgettext("picard-countries", "United States"),
    u"UM": dgettext("picard-countries", "United States Minor Outlying Islands"),
    u"UY": dgettext("picard-countries", "Uruguay"),
    u"UZ": dgettext("picard-countries", "Uzbekistan"),
    u"VU": dgettext("picard-countries", "Vanuatu"),
    u"VA": dgettext("picard-countries", "Vatican City State (Holy See)"),
    u"VN": dgettext("picard-countries", "Viet Nam"),
    u"EH": dgettext("picard-countries", "Western Sahara"),
    u"YE": dgettext("picard-countries", "Yemen"),
    u"ZM": dgettext("picard-countries", "Zambia"),
    u"ZW": dgettext("picard-countries", "Zimbabwe"),
    u"TW": dgettext("picard-countries", "Taiwan"),
    u"XW": dgettext("picard-countries", "[Worldwide]"),
    u"XE": dgettext("picard-countries", "Europe"),
    u"SU": dgettext("picard-countries", "Soviet Union (historical, 1922-1991)"),
    u"XG": dgettext("picard-countries", "East Germany (historical, 1949-1990)"),
    u"XC": dgettext("picard-countries", "Czechoslovakia (historical, 1918-1992)"),
    u"CD": dgettext("picard-countries", "Congo, The Democratic Republic of the"),
    u"SK": dgettext("picard-countries", "Slovakia"),
    u"BA": dgettext("picard-countries", "Bosnia and Herzegovina"),
    u"KP": dgettext("picard-countries", "Korea (North), Democratic People's Republic of"),
    u"KR": dgettext("picard-countries", "Korea (South), Republic of"),
    u"ME": dgettext("picard-countries", "Montenegro"),
    u"GS": dgettext("picard-countries", "South Georgia and the South Sandwich Islands"),
    u"PS": dgettext("picard-countries", "Palestinian Territory"),
    u"MO": dgettext("picard-countries", "Macao"),
    u"TL": dgettext("picard-countries", "Timor-Leste"),
    u"AX": dgettext("picard-countries", "Åland Islands"),
    u"GG": dgettext("picard-countries", "Guernsey"),
    u"IM": dgettext("picard-countries", "Isle of Man"),
    u"JE": dgettext("picard-countries", "Jersey"),
    u"RS": dgettext("picard-countries", "Serbia"),
    u"BL": dgettext("picard-countries", "Saint Barthélemy"),
    u"YU": dgettext("picard-countries", "Yugoslavia (historical, 1918-2003)"),
    u"CS": dgettext("picard-countries", "Serbia and Montenegro (historical, 2003-2006)"),
    u"CI": dgettext("picard-countries", "Côte d'Ivoire"),
    u"HM": dgettext("picard-countries", "Heard Island and McDonald Islands"),
    u"IR": dgettext("picard-countries", "Iran, Islamic Republic of"),
    u"PM": dgettext("picard-countries", "Saint Pierre and Miquelon"),
    u"SJ": dgettext("picard-countries", "Svalbard and Jan Mayen"),
    u"SS": dgettext("picard-countries", "South Sudan"),
    u"BQ": dgettext("picard-countries", "Bonaire, Sint Eustatius and Saba"),
    u"CW": dgettext("picard-countries", "Curaçao"),
    u"SX": dgettext("picard-countries", "Sint Maarten (Dutch part)"),
    u"AN": dgettext("picard-countries", "Netherlands Antilles (historical, 1954-2010)"),
    u"SH": dgettext("picard-countries", "Saint Helena, Ascension and Tristan da Cunha"),
    u"BO": dgettext("picard-countries", "Bolivia, Plurinational State of"),
    u"VE": dgettext("picard-countries", "Venezuela, Bolivarian Republic of"),
    u"MD": dgettext("picard-countries", "Moldova, Republic of"),
    u"RE": dgettext("picard-countries", "Réunion"),
    u"MF": dgettext("picard-countries", "Saint Martin (French part)"),
}