# -*- coding: utf-8 -*-
#
# Picard, the next-generation MusicBrainz tagger
#
# Copyright (C) 2026 Laurent Monin
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

"""Match quality icons.

Provides pre-rendered bookmark icons indicating match quality.  Icons are
generated by ``scripts/generate_match_icons.py`` and shipped as static PNGs
in the Qt resource system.

There are 6 levels (indices 0–5):

  Level 0 : similarity < 0.5625  (poor match, 6 px red fill)
  Level 1 : 0.5625 ≤ sim < 0.6719
  Level 2 : 0.6719 ≤ sim < 0.7812
  Level 3 : 0.7812 ≤ sim < 0.8906
  Level 4 : 0.8906 ≤ sim < 1.0
  Level 5 : sim == 1.0 exactly   (perfect match, fully green)

Use :func:`similarity_to_level` to convert a float similarity to a level
index, then index into :data:`match_icons` or :data:`match_pending_icons`.
"""

import bisect

from PyQt6 import QtGui


# ---------------------------------------------------------------------------
# Level configuration — also imported by scripts/tools/generate_match_icons.py
# ---------------------------------------------------------------------------

# Similarities below this threshold all map to the same "poor match" icon.
LOW_THRESHOLD = 0.5625

# Number of distinct fill levels between "poor match" and "perfect match".
NUM_STEPS = 4

# Total number of distinct icon levels: low + NUM_STEPS + perfect (1.0).
NUM_LEVELS = NUM_STEPS + 2

# Thresholds dividing the range [LOW_THRESHOLD, 1.0) into NUM_STEPS equal
# buckets.  Level 0 = below LOW_THRESHOLD, last level = exact 1.0.
_BUCKET_WIDTH = (1.0 - LOW_THRESHOLD) / NUM_STEPS
_THRESHOLDS = tuple(LOW_THRESHOLD + i * _BUCKET_WIDTH for i in range(1, NUM_STEPS))


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def similarity_to_level(similarity: float) -> int:
    """Convert a similarity score to a level index (0–5).

    Level 0 is the lowest (poor match), level 5 is exact match (1.0 only).
    """
    if similarity >= 1.0:
        return NUM_LEVELS - 1
    if similarity < LOW_THRESHOLD:
        return 0
    return bisect.bisect_right(_THRESHOLDS, similarity) + 1


# Icons are loaded once on first access.
match_icons: list[QtGui.QIcon] = []
match_pending_icons: list[QtGui.QIcon] = []


def load_match_icons() -> None:
    """Load match icons from Qt resources.  Call after QApplication is created."""
    match_icons.clear()
    match_pending_icons.clear()
    for i in range(NUM_LEVELS):
        match_icons.append(QtGui.QIcon(f":/images/match-{i}.png"))
        match_pending_icons.append(QtGui.QIcon(f":/images/match-pending-{i}.png"))
