# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ReleasesOptionsPage(object):
    def setupUi(self, ReleasesOptionsPage):
        ReleasesOptionsPage.setObjectName(_fromUtf8("ReleasesOptionsPage"))
        ReleasesOptionsPage.resize(551, 497)
        self.verticalLayout_3 = QtGui.QVBoxLayout(ReleasesOptionsPage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.type_group = QtGui.QGroupBox(ReleasesOptionsPage)
        self.type_group.setObjectName(_fromUtf8("type_group"))
        self.gridLayout = QtGui.QGridLayout(self.type_group)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3.addWidget(self.type_group)
        self.country_group = QtGui.QGroupBox(ReleasesOptionsPage)
        self.country_group.setObjectName(_fromUtf8("country_group"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.country_group)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.country_list = QtGui.QListWidget(self.country_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.country_list.sizePolicy().hasHeightForWidth())
        self.country_list.setSizePolicy(sizePolicy)
        self.country_list.setObjectName(_fromUtf8("country_list"))
        self.horizontalLayout.addWidget(self.country_list)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.add_countries = QtGui.QPushButton(self.country_group)
        self.add_countries.setObjectName(_fromUtf8("add_countries"))
        self.verticalLayout.addWidget(self.add_countries)
        self.remove_countries = QtGui.QPushButton(self.country_group)
        self.remove_countries.setObjectName(_fromUtf8("remove_countries"))
        self.verticalLayout.addWidget(self.remove_countries)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.preferred_country_list = QtGui.QListWidget(self.country_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preferred_country_list.sizePolicy().hasHeightForWidth())
        self.preferred_country_list.setSizePolicy(sizePolicy)
        self.preferred_country_list.setDragEnabled(True)
        self.preferred_country_list.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.preferred_country_list.setObjectName(_fromUtf8("preferred_country_list"))
        self.horizontalLayout.addWidget(self.preferred_country_list)
        self.verticalLayout_3.addWidget(self.country_group)
        self.format_group = QtGui.QGroupBox(ReleasesOptionsPage)
        self.format_group.setObjectName(_fromUtf8("format_group"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.format_group)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.format_list = QtGui.QListWidget(self.format_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_list.sizePolicy().hasHeightForWidth())
        self.format_list.setSizePolicy(sizePolicy)
        self.format_list.setObjectName(_fromUtf8("format_list"))
        self.horizontalLayout_2.addWidget(self.format_list)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.add_formats = QtGui.QPushButton(self.format_group)
        self.add_formats.setObjectName(_fromUtf8("add_formats"))
        self.verticalLayout_2.addWidget(self.add_formats)
        self.remove_formats = QtGui.QPushButton(self.format_group)
        self.remove_formats.setObjectName(_fromUtf8("remove_formats"))
        self.verticalLayout_2.addWidget(self.remove_formats)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.preferred_format_list = QtGui.QListWidget(self.format_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preferred_format_list.sizePolicy().hasHeightForWidth())
        self.preferred_format_list.setSizePolicy(sizePolicy)
        self.preferred_format_list.setDragEnabled(True)
        self.preferred_format_list.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.preferred_format_list.setObjectName(_fromUtf8("preferred_format_list"))
        self.horizontalLayout_2.addWidget(self.preferred_format_list)
        self.verticalLayout_3.addWidget(self.format_group)

        self.retranslateUi(ReleasesOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(ReleasesOptionsPage)

    def retranslateUi(self, ReleasesOptionsPage):
        self.type_group.setTitle(_("Preferred release types"))
        self.country_group.setTitle(_("Preferred release countries"))
        self.add_countries.setText(_(">"))
        self.remove_countries.setText(_("<"))
        self.format_group.setTitle(_("Preferred release formats"))
        self.add_formats.setText(_(">"))
        self.remove_formats.setText(_("<"))

