# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/options_matching.ui'
#
# Created: Thu May 12 23:52:13 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MatchingOptionsPage(object):
    def setupUi(self, MatchingOptionsPage):
        MatchingOptionsPage.setObjectName("MatchingOptionsPage")
        MatchingOptionsPage.resize(382, 498)
        self.vboxlayout = QtGui.QVBoxLayout(MatchingOptionsPage)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName("vboxlayout")
        self.rename_files = QtGui.QGroupBox(MatchingOptionsPage)
        self.rename_files.setObjectName("rename_files")
        self.gridlayout = QtGui.QGridLayout(self.rename_files)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(2)
        self.gridlayout.setObjectName("gridlayout")
        self.label_6 = QtGui.QLabel(self.rename_files)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridlayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.track_matching_threshold = QtGui.QSpinBox(self.rename_files)
        self.track_matching_threshold.setMaximum(100)
        self.track_matching_threshold.setObjectName("track_matching_threshold")
        self.gridlayout.addWidget(self.track_matching_threshold, 2, 1, 1, 1)
        self.cluster_lookup_threshold = QtGui.QSpinBox(self.rename_files)
        self.cluster_lookup_threshold.setMaximum(100)
        self.cluster_lookup_threshold.setObjectName("cluster_lookup_threshold")
        self.gridlayout.addWidget(self.cluster_lookup_threshold, 1, 1, 1, 1)
        self.file_lookup_threshold = QtGui.QSpinBox(self.rename_files)
        self.file_lookup_threshold.setMaximum(100)
        self.file_lookup_threshold.setObjectName("file_lookup_threshold")
        self.gridlayout.addWidget(self.file_lookup_threshold, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.rename_files)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.rename_files)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridlayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.vboxlayout.addWidget(self.rename_files)
        self.groupBox = QtGui.QGroupBox(MatchingOptionsPage)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.prefer_album_score = QtGui.QSlider(self.groupBox)
        self.prefer_album_score.setMaximum(100)
        self.prefer_album_score.setProperty("value", 50)
        self.prefer_album_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_album_score.setObjectName("prefer_album_score")
        self.gridLayout.addWidget(self.prefer_album_score, 0, 2, 1, 1)
        self.prefer_single_score = QtGui.QSlider(self.groupBox)
        self.prefer_single_score.setMaximum(100)
        self.prefer_single_score.setProperty("value", 50)
        self.prefer_single_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_single_score.setObjectName("prefer_single_score")
        self.gridLayout.addWidget(self.prefer_single_score, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.prefer_ep_score = QtGui.QSlider(self.groupBox)
        self.prefer_ep_score.setMaximum(100)
        self.prefer_ep_score.setProperty("value", 50)
        self.prefer_ep_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_ep_score.setObjectName("prefer_ep_score")
        self.gridLayout.addWidget(self.prefer_ep_score, 2, 2, 1, 1)
        self.prefer_compilation_score = QtGui.QSlider(self.groupBox)
        self.prefer_compilation_score.setMaximum(100)
        self.prefer_compilation_score.setProperty("value", 50)
        self.prefer_compilation_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_compilation_score.setObjectName("prefer_compilation_score")
        self.gridLayout.addWidget(self.prefer_compilation_score, 3, 2, 1, 1)
        self.prefer_soundtrack_score = QtGui.QSlider(self.groupBox)
        self.prefer_soundtrack_score.setMaximum(100)
        self.prefer_soundtrack_score.setProperty("value", 50)
        self.prefer_soundtrack_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_soundtrack_score.setObjectName("prefer_soundtrack_score")
        self.gridLayout.addWidget(self.prefer_soundtrack_score, 4, 2, 1, 1)
        self.prefer_spokenword_score = QtGui.QSlider(self.groupBox)
        self.prefer_spokenword_score.setMaximum(100)
        self.prefer_spokenword_score.setProperty("value", 50)
        self.prefer_spokenword_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_spokenword_score.setObjectName("prefer_spokenword_score")
        self.gridLayout.addWidget(self.prefer_spokenword_score, 5, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.prefer_interview_score = QtGui.QSlider(self.groupBox)
        self.prefer_interview_score.setMaximum(100)
        self.prefer_interview_score.setProperty("value", 50)
        self.prefer_interview_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_interview_score.setObjectName("prefer_interview_score")
        self.gridLayout.addWidget(self.prefer_interview_score, 6, 2, 1, 1)
        self.prefer_audiobook_score = QtGui.QSlider(self.groupBox)
        self.prefer_audiobook_score.setMaximum(100)
        self.prefer_audiobook_score.setProperty("value", 50)
        self.prefer_audiobook_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_audiobook_score.setObjectName("prefer_audiobook_score")
        self.gridLayout.addWidget(self.prefer_audiobook_score, 7, 2, 1, 1)
        self.prefer_live_score = QtGui.QSlider(self.groupBox)
        self.prefer_live_score.setMaximum(100)
        self.prefer_live_score.setProperty("value", 50)
        self.prefer_live_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_live_score.setObjectName("prefer_live_score")
        self.gridLayout.addWidget(self.prefer_live_score, 8, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 0, 1, 1)
        self.prefer_remix_score = QtGui.QSlider(self.groupBox)
        self.prefer_remix_score.setMaximum(100)
        self.prefer_remix_score.setProperty("value", 50)
        self.prefer_remix_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_remix_score.setObjectName("prefer_remix_score")
        self.gridLayout.addWidget(self.prefer_remix_score, 9, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 0, 1, 1)
        self.prefer_other_score = QtGui.QSlider(self.groupBox)
        self.prefer_other_score.setMaximum(100)
        self.prefer_other_score.setSliderPosition(50)
        self.prefer_other_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_other_score.setObjectName("prefer_other_score")
        self.gridLayout.addWidget(self.prefer_other_score, 10, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 10, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.reset_preferred_types_btn = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_preferred_types_btn.sizePolicy().hasHeightForWidth())
        self.reset_preferred_types_btn.setSizePolicy(sizePolicy)
        self.reset_preferred_types_btn.setObjectName("reset_preferred_types_btn")
        self.horizontalLayout.addWidget(self.reset_preferred_types_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 12, 2, 1, 1)
        self.vboxlayout.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 41, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)
        self.label_6.setBuddy(self.file_lookup_threshold)
        self.label_4.setBuddy(self.file_lookup_threshold)
        self.label_5.setBuddy(self.file_lookup_threshold)

        self.retranslateUi(MatchingOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(MatchingOptionsPage)
        MatchingOptionsPage.setTabOrder(self.file_lookup_threshold, self.cluster_lookup_threshold)
        MatchingOptionsPage.setTabOrder(self.cluster_lookup_threshold, self.track_matching_threshold)

    def retranslateUi(self, MatchingOptionsPage):
        self.rename_files.setTitle(_("Thresholds"))
        self.label_6.setText(_("Minimal similarity for matching files to tracks:"))
        self.track_matching_threshold.setSuffix(_(" %"))
        self.cluster_lookup_threshold.setSuffix(_(" %"))
        self.file_lookup_threshold.setSuffix(_(" %"))
        self.label_4.setText(_("Minimal similarity for file lookups:"))
        self.label_5.setText(_("Minimal similarity for cluster lookups:"))
        self.groupBox.setTitle(_("Preferred release types"))
        self.label.setText(_("Album"))
        self.label_2.setText(_("Single"))
        self.label_3.setText(_("EP"))
        self.label_7.setText(_("Compilation"))
        self.label_8.setText(_("Soundtrack"))
        self.label_9.setText(_("Spokenword"))
        self.label_10.setText(_("Interview"))
        self.label_11.setText(_("Audiobook"))
        self.label_12.setText(_("Live"))
        self.label_13.setText(_("Remix"))
        self.label_14.setText(_("Other"))
        self.reset_preferred_types_btn.setText(_("Reset all"))

