# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/options_moving.ui'
#
# Created: Wed May  2 15:01:19 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MovingOptionsPage(object):
    def setupUi(self, MovingOptionsPage):
        MovingOptionsPage.setObjectName(_fromUtf8("MovingOptionsPage"))
        MovingOptionsPage.resize(504, 563)
        self.gridlayout = QtGui.QGridLayout(MovingOptionsPage)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        spacerItem = QtGui.QSpacerItem(378, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem, 8, 0, 1, 1)
        self.move_additional_files_pattern = QtGui.QLineEdit(MovingOptionsPage)
        self.move_additional_files_pattern.setObjectName(_fromUtf8("move_additional_files_pattern"))
        self.gridlayout.addWidget(self.move_additional_files_pattern, 5, 0, 1, 1)
        self.move_additional_files = QtGui.QCheckBox(MovingOptionsPage)
        self.move_additional_files.setObjectName(_fromUtf8("move_additional_files"))
        self.gridlayout.addWidget(self.move_additional_files, 4, 0, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(2)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.move_files_to = QtGui.QLineEdit(MovingOptionsPage)
        self.move_files_to.setObjectName(_fromUtf8("move_files_to"))
        self.hboxlayout.addWidget(self.move_files_to)
        self.move_files_to_browse = QtGui.QPushButton(MovingOptionsPage)
        self.move_files_to_browse.setObjectName(_fromUtf8("move_files_to_browse"))
        self.hboxlayout.addWidget(self.move_files_to_browse)
        self.gridlayout.addLayout(self.hboxlayout, 2, 0, 1, 1)
        self.delete_empty_dirs = QtGui.QCheckBox(MovingOptionsPage)
        self.delete_empty_dirs.setObjectName(_fromUtf8("delete_empty_dirs"))
        self.gridlayout.addWidget(self.delete_empty_dirs, 3, 0, 1, 1)
        self.move_files = QtGui.QCheckBox(MovingOptionsPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.move_files.sizePolicy().hasHeightForWidth())
        self.move_files.setSizePolicy(sizePolicy)
        self.move_files.setObjectName(_fromUtf8("move_files"))
        self.gridlayout.addWidget(self.move_files, 1, 0, 1, 1)
        self.moving_files_2 = QtGui.QGroupBox(MovingOptionsPage)
        self.moving_files_2.setObjectName(_fromUtf8("moving_files_2"))
        self.vboxlayout = QtGui.QVBoxLayout(self.moving_files_2)
        self.vboxlayout.setSpacing(2)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.groupBox = QtGui.QGroupBox(self.moving_files_2)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.link_type_none = QtGui.QRadioButton(self.groupBox)
        self.link_type_none.setObjectName(_fromUtf8("link_type_none"))
        self.horizontalLayout.addWidget(self.link_type_none)
        self.link_type_hard = QtGui.QRadioButton(self.groupBox)
        self.link_type_hard.setObjectName(_fromUtf8("link_type_hard"))
        self.horizontalLayout.addWidget(self.link_type_hard)
        self.link_type_soft = QtGui.QRadioButton(self.groupBox)
        self.link_type_soft.setObjectName(_fromUtf8("link_type_soft"))
        self.horizontalLayout.addWidget(self.link_type_soft)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_1 = QtGui.QLabel(self.groupBox)
        self.label_1.setText(_fromUtf8(""))
        self.label_1.setWordWrap(True)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.horizontalLayout.addWidget(self.label_1)
        self.vboxlayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.moving_files_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.link_filename_old = QtGui.QRadioButton(self.groupBox_2)
        self.link_filename_old.setObjectName(_fromUtf8("link_filename_old"))
        self.horizontalLayout_2.addWidget(self.link_filename_old)
        self.link_filename_new = QtGui.QRadioButton(self.groupBox_2)
        self.link_filename_new.setObjectName(_fromUtf8("link_filename_new"))
        self.horizontalLayout_2.addWidget(self.link_filename_new)
        self.link_filename_both = QtGui.QRadioButton(self.groupBox_2)
        self.link_filename_both.setObjectName(_fromUtf8("link_filename_both"))
        self.horizontalLayout_2.addWidget(self.link_filename_both)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.vboxlayout.addWidget(self.groupBox_2)
        self.gridlayout.addWidget(self.moving_files_2, 6, 0, 1, 1)

        self.retranslateUi(MovingOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(MovingOptionsPage)

    def retranslateUi(self, MovingOptionsPage):
        self.move_additional_files.setText(_("Move additional files:"))
        self.move_files_to_browse.setText(_("Browse..."))
        self.delete_empty_dirs.setText(_("Delete empty directories"))
        self.move_files.setText(_("Move files to this directory when saving:"))
        self.moving_files_2.setTitle(_("Creating links in source directory"))
        self.groupBox.setTitle(_("Link type"))
        self.link_type_none.setText(_("None"))
        self.link_type_hard.setText(_("Hard"))
        self.link_type_soft.setText(_("Symlink (Soft)"))
        self.groupBox_2.setTitle(_("Link name"))
        self.link_filename_old.setText(_("Source file"))
        self.link_filename_new.setText(_("Renamed file"))
        self.link_filename_both.setText(_("Both"))

