# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/options_tags.ui'
#
# Created: Wed Feb 25 00:05:34 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TagsOptionsPage(object):
    def setupUi(self, TagsOptionsPage):
        TagsOptionsPage.setObjectName("TagsOptionsPage")
        TagsOptionsPage.resize(463, 388)
        self.vboxlayout = QtGui.QVBoxLayout(TagsOptionsPage)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName("vboxlayout")
        self.dont_write_tags = QtGui.QCheckBox(TagsOptionsPage)
        self.dont_write_tags.setObjectName("dont_write_tags")
        self.vboxlayout.addWidget(self.dont_write_tags)
        self.rename_files = QtGui.QGroupBox(TagsOptionsPage)
        self.rename_files.setObjectName("rename_files")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.rename_files)
        self.vboxlayout1.setSpacing(2)
        self.vboxlayout1.setMargin(9)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.clear_existing_tags = QtGui.QCheckBox(self.rename_files)
        self.clear_existing_tags.setObjectName("clear_existing_tags")
        self.vboxlayout1.addWidget(self.clear_existing_tags)
        self.remove_id3_from_flac = QtGui.QCheckBox(self.rename_files)
        self.remove_id3_from_flac.setObjectName("remove_id3_from_flac")
        self.vboxlayout1.addWidget(self.remove_id3_from_flac)
        self.remove_ape_from_mp3 = QtGui.QCheckBox(self.rename_files)
        self.remove_ape_from_mp3.setObjectName("remove_ape_from_mp3")
        self.vboxlayout1.addWidget(self.remove_ape_from_mp3)
        self.vboxlayout.addWidget(self.rename_files)
        self.rename_files_2 = QtGui.QGroupBox(TagsOptionsPage)
        self.rename_files_2.setObjectName("rename_files_2")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.rename_files_2)
        self.vboxlayout2.setSpacing(2)
        self.vboxlayout2.setMargin(9)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.groupBox = QtGui.QGroupBox(self.rename_files_2)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.write_id3v24 = QtGui.QRadioButton(self.groupBox)
        self.write_id3v24.setChecked(True)
        self.write_id3v24.setObjectName("write_id3v24")
        self.horizontalLayout.addWidget(self.write_id3v24)
        self.write_id3v23 = QtGui.QRadioButton(self.groupBox)
        self.write_id3v23.setChecked(False)
        self.write_id3v23.setObjectName("write_id3v23")
        self.horizontalLayout.addWidget(self.write_id3v23)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.vboxlayout2.addWidget(self.groupBox)
        self.write_id3v1 = QtGui.QCheckBox(self.rename_files_2)
        self.write_id3v1.setObjectName("write_id3v1")
        self.vboxlayout2.addWidget(self.write_id3v1)
        self.groupBox_2 = QtGui.QGroupBox(self.rename_files_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.enc_utf8 = QtGui.QRadioButton(self.groupBox_2)
        self.enc_utf8.setObjectName("enc_utf8")
        self.horizontalLayout_2.addWidget(self.enc_utf8)
        self.enc_utf16 = QtGui.QRadioButton(self.groupBox_2)
        self.enc_utf16.setObjectName("enc_utf16")
        self.horizontalLayout_2.addWidget(self.enc_utf16)
        self.enc_iso88591 = QtGui.QRadioButton(self.groupBox_2)
        self.enc_iso88591.setObjectName("enc_iso88591")
        self.horizontalLayout_2.addWidget(self.enc_iso88591)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.vboxlayout2.addWidget(self.groupBox_2)
        self.vboxlayout.addWidget(self.rename_files_2)
        spacerItem2 = QtGui.QSpacerItem(274, 41, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem2)

        self.retranslateUi(TagsOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(TagsOptionsPage)

    def retranslateUi(self, TagsOptionsPage):
        self.dont_write_tags.setText(_("Do not write tags to files"))
        self.rename_files.setTitle(_("Before tagging"))
        self.clear_existing_tags.setText(_("Clear existing tags"))
        self.remove_id3_from_flac.setText(_("Remove ID3 tags from FLAC files"))
        self.remove_ape_from_mp3.setText(_("Remove APEv2 tags from MP3 files"))
        self.rename_files_2.setTitle(_("Tag compatibility"))
        self.groupBox.setTitle(_("ID3v2 version"))
        self.write_id3v24.setText(_("2.4"))
        self.write_id3v23.setText(_("2.3"))
        self.write_id3v1.setText(_("Also include ID3v1 tags in the files"))
        self.groupBox_2.setTitle(_("ID3v2 text encoding"))
        self.enc_utf8.setText(_("UTF-8"))
        self.enc_utf16.setText(_("UTF-16"))
        self.enc_iso88591.setText(_("ISO-8859-1"))

