# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InterfaceOptionsPage(object):
    def setupUi(self, InterfaceOptionsPage):
        InterfaceOptionsPage.setObjectName(_fromUtf8("InterfaceOptionsPage"))
        InterfaceOptionsPage.resize(466, 500)
        self.vboxlayout = QtGui.QVBoxLayout(InterfaceOptionsPage)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.groupBox_2 = QtGui.QGroupBox(InterfaceOptionsPage)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox_2)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.toolbar_show_labels = QtGui.QCheckBox(self.groupBox_2)
        self.toolbar_show_labels.setObjectName(_fromUtf8("toolbar_show_labels"))
        self.vboxlayout1.addWidget(self.toolbar_show_labels)
        self.toolbar_multiselect = QtGui.QCheckBox(self.groupBox_2)
        self.toolbar_multiselect.setObjectName(_fromUtf8("toolbar_multiselect"))
        self.vboxlayout1.addWidget(self.toolbar_multiselect)
        self.builtin_search = QtGui.QCheckBox(self.groupBox_2)
        self.builtin_search.setObjectName(_fromUtf8("builtin_search"))
        self.vboxlayout1.addWidget(self.builtin_search)
        self.use_adv_search_syntax = QtGui.QCheckBox(self.groupBox_2)
        self.use_adv_search_syntax.setObjectName(_fromUtf8("use_adv_search_syntax"))
        self.vboxlayout1.addWidget(self.use_adv_search_syntax)
        self.quit_confirmation = QtGui.QCheckBox(self.groupBox_2)
        self.quit_confirmation.setObjectName(_fromUtf8("quit_confirmation"))
        self.vboxlayout1.addWidget(self.quit_confirmation)
        self.starting_directory = QtGui.QCheckBox(self.groupBox_2)
        self.starting_directory.setObjectName(_fromUtf8("starting_directory"))
        self.vboxlayout1.addWidget(self.starting_directory)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.starting_directory_path = QtGui.QLineEdit(self.groupBox_2)
        self.starting_directory_path.setEnabled(False)
        self.starting_directory_path.setObjectName(_fromUtf8("starting_directory_path"))
        self.horizontalLayout_4.addWidget(self.starting_directory_path)
        self.starting_directory_browse = QtGui.QPushButton(self.groupBox_2)
        self.starting_directory_browse.setEnabled(False)
        self.starting_directory_browse.setObjectName(_fromUtf8("starting_directory_browse"))
        self.horizontalLayout_4.addWidget(self.starting_directory_browse)
        self.vboxlayout1.addLayout(self.horizontalLayout_4)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.vboxlayout1.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ui_language = QtGui.QComboBox(self.groupBox_2)
        self.ui_language.setObjectName(_fromUtf8("ui_language"))
        self.horizontalLayout.addWidget(self.ui_language)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.vboxlayout1.addLayout(self.horizontalLayout)
        self.vboxlayout.addWidget(self.groupBox_2)
        self.customize_toolbar_box = QtGui.QGroupBox(InterfaceOptionsPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customize_toolbar_box.sizePolicy().hasHeightForWidth())
        self.customize_toolbar_box.setSizePolicy(sizePolicy)
        self.customize_toolbar_box.setObjectName(_fromUtf8("customize_toolbar_box"))
        self.verticalLayout = QtGui.QVBoxLayout(self.customize_toolbar_box)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolbar_layout_list = QtGui.QListWidget(self.customize_toolbar_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar_layout_list.sizePolicy().hasHeightForWidth())
        self.toolbar_layout_list.setSizePolicy(sizePolicy)
        self.toolbar_layout_list.setObjectName(_fromUtf8("toolbar_layout_list"))
        self.verticalLayout.addWidget(self.toolbar_layout_list)
        self.edit_button_box = QtGui.QWidget(self.customize_toolbar_box)
        self.edit_button_box.setObjectName(_fromUtf8("edit_button_box"))
        self.edit_box_layout = QtGui.QHBoxLayout(self.edit_button_box)
        self.edit_box_layout.setMargin(0)
        self.edit_box_layout.setObjectName(_fromUtf8("edit_box_layout"))
        self.add_button = QtGui.QPushButton(self.edit_button_box)
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.edit_box_layout.addWidget(self.add_button)
        self.insert_separator_button = QtGui.QPushButton(self.edit_button_box)
        self.insert_separator_button.setObjectName(_fromUtf8("insert_separator_button"))
        self.edit_box_layout.addWidget(self.insert_separator_button)
        spacerItem1 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.edit_box_layout.addItem(spacerItem1)
        self.up_button = QtGui.QToolButton(self.edit_button_box)
        self.up_button.setArrowType(QtCore.Qt.UpArrow)
        self.up_button.setObjectName(_fromUtf8("up_button"))
        self.edit_box_layout.addWidget(self.up_button)
        self.down_button = QtGui.QToolButton(self.edit_button_box)
        self.down_button.setArrowType(QtCore.Qt.DownArrow)
        self.down_button.setObjectName(_fromUtf8("down_button"))
        self.edit_box_layout.addWidget(self.down_button)
        self.remove_button = QtGui.QPushButton(self.edit_button_box)
        self.remove_button.setObjectName(_fromUtf8("remove_button"))
        self.edit_box_layout.addWidget(self.remove_button)
        self.verticalLayout.addWidget(self.edit_button_box)
        self.vboxlayout.addWidget(self.customize_toolbar_box)

        self.retranslateUi(InterfaceOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(InterfaceOptionsPage)

    def retranslateUi(self, InterfaceOptionsPage):
        self.groupBox_2.setTitle(_("Miscellaneous"))
        self.toolbar_show_labels.setText(_("Show text labels under icons"))
        self.toolbar_multiselect.setText(_("Allow selection of multiple directories"))
        self.builtin_search.setText(_("Use builtin search rather than looking in browser"))
        self.use_adv_search_syntax.setText(_("Use advanced query syntax"))
        self.quit_confirmation.setText(_("Show a quit confirmation dialog for unsaved changes"))
        self.starting_directory.setText(_("Begin browsing in the following directory:"))
        self.starting_directory_browse.setText(_("Browse..."))
        self.label.setText(_("User interface language:"))
        self.customize_toolbar_box.setTitle(_("Customize Action Toolbar"))
        self.add_button.setToolTip(_("Add a new button to Toolbar"))
        self.add_button.setText(_("Add Action"))
        self.insert_separator_button.setToolTip(_("Insert a separator"))
        self.insert_separator_button.setText(_("Add Separator"))
        self.up_button.setToolTip(_("Move selected item up"))
        self.up_button.setText(_("..."))
        self.down_button.setToolTip(_("Move selected item down"))
        self.down_button.setText(_("..."))
        self.remove_button.setToolTip(_("Remove button from toolbar"))
        self.remove_button.setText(_("Remove"))

