# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FolksonomyOptionsPage(object):
    def setupUi(self, FolksonomyOptionsPage):
        FolksonomyOptionsPage.setObjectName("FolksonomyOptionsPage")
        FolksonomyOptionsPage.resize(590, 304)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FolksonomyOptionsPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rename_files_3 = QtWidgets.QGroupBox(FolksonomyOptionsPage)
        self.rename_files_3.setObjectName("rename_files_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rename_files_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ignore_tags_2 = QtWidgets.QLabel(self.rename_files_3)
        self.ignore_tags_2.setObjectName("ignore_tags_2")
        self.verticalLayout.addWidget(self.ignore_tags_2)
        self.ignore_tags = QtWidgets.QLineEdit(self.rename_files_3)
        self.ignore_tags.setObjectName("ignore_tags")
        self.verticalLayout.addWidget(self.ignore_tags)
        self.only_my_tags = QtWidgets.QCheckBox(self.rename_files_3)
        self.only_my_tags.setObjectName("only_my_tags")
        self.verticalLayout.addWidget(self.only_my_tags)
        self.artists_tags = QtWidgets.QCheckBox(self.rename_files_3)
        self.artists_tags.setEnabled(True)
        self.artists_tags.setObjectName("artists_tags")
        self.verticalLayout.addWidget(self.artists_tags)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_5 = QtWidgets.QLabel(self.rename_files_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.hboxlayout.addWidget(self.label_5)
        self.min_tag_usage = QtWidgets.QSpinBox(self.rename_files_3)
        self.min_tag_usage.setMaximum(100)
        self.min_tag_usage.setObjectName("min_tag_usage")
        self.hboxlayout.addWidget(self.min_tag_usage)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_6 = QtWidgets.QLabel(self.rename_files_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.hboxlayout1.addWidget(self.label_6)
        self.max_tags = QtWidgets.QSpinBox(self.rename_files_3)
        self.max_tags.setMaximum(100)
        self.max_tags.setObjectName("max_tags")
        self.hboxlayout1.addWidget(self.max_tags)
        self.verticalLayout.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.ignore_tags_4 = QtWidgets.QLabel(self.rename_files_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ignore_tags_4.sizePolicy().hasHeightForWidth())
        self.ignore_tags_4.setSizePolicy(sizePolicy)
        self.ignore_tags_4.setObjectName("ignore_tags_4")
        self.hboxlayout2.addWidget(self.ignore_tags_4)
        self.join_tags = QtWidgets.QComboBox(self.rename_files_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.join_tags.sizePolicy().hasHeightForWidth())
        self.join_tags.setSizePolicy(sizePolicy)
        self.join_tags.setEditable(True)
        self.join_tags.setObjectName("join_tags")
        self.join_tags.addItem("")
        self.join_tags.setItemText(0, "")
        self.join_tags.addItem("")
        self.join_tags.addItem("")
        self.hboxlayout2.addWidget(self.join_tags)
        self.verticalLayout.addLayout(self.hboxlayout2)
        self.verticalLayout_2.addWidget(self.rename_files_3)
        spacerItem = QtWidgets.QSpacerItem(181, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_5.setBuddy(self.min_tag_usage)
        self.label_6.setBuddy(self.min_tag_usage)

        self.retranslateUi(FolksonomyOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(FolksonomyOptionsPage)

    def retranslateUi(self, FolksonomyOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.rename_files_3.setTitle(_("Folksonomy Tags"))
        self.ignore_tags_2.setText(_("Ignore tags:"))
        self.only_my_tags.setText(_("Only use my tags"))
        self.artists_tags.setText(_("Fall back on album\'s artists tags if no tags are found for the release or release group"))
        self.label_5.setText(_("Minimal tag usage:"))
        self.min_tag_usage.setSuffix(_(" %"))
        self.label_6.setText(_("Maximum number of tags:"))
        self.ignore_tags_4.setText(_("Join multiple tags with:"))
        self.join_tags.setItemText(1, _(" / "))
        self.join_tags.setItemText(2, _(", "))

