# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/options_releases.ui'
#
# Created: Fri Jul 13 15:18:48 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ReleasesOptionsPage(object):
    def setupUi(self, ReleasesOptionsPage):
        ReleasesOptionsPage.setObjectName(_fromUtf8("ReleasesOptionsPage"))
        ReleasesOptionsPage.resize(551, 497)
        self.verticalLayout_3 = QtGui.QVBoxLayout(ReleasesOptionsPage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.type_group = QtGui.QGroupBox(ReleasesOptionsPage)
        self.type_group.setObjectName(_fromUtf8("type_group"))
        self.gridLayout = QtGui.QGridLayout(self.type_group)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.type_group)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.prefer_album_score = QtGui.QSlider(self.type_group)
        self.prefer_album_score.setMaximum(100)
        self.prefer_album_score.setProperty(_fromUtf8("value"), 50)
        self.prefer_album_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_album_score.setObjectName(_fromUtf8("prefer_album_score"))
        self.gridLayout.addWidget(self.prefer_album_score, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.type_group)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.prefer_single_score = QtGui.QSlider(self.type_group)
        self.prefer_single_score.setMaximum(100)
        self.prefer_single_score.setProperty(_fromUtf8("value"), 50)
        self.prefer_single_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_single_score.setObjectName(_fromUtf8("prefer_single_score"))
        self.gridLayout.addWidget(self.prefer_single_score, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.type_group)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.prefer_ep_score = QtGui.QSlider(self.type_group)
        self.prefer_ep_score.setMaximum(100)
        self.prefer_ep_score.setProperty(_fromUtf8("value"), 50)
        self.prefer_ep_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_ep_score.setObjectName(_fromUtf8("prefer_ep_score"))
        self.gridLayout.addWidget(self.prefer_ep_score, 0, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.type_group)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.prefer_compilation_score = QtGui.QSlider(self.type_group)
        self.prefer_compilation_score.setMaximum(100)
        self.prefer_compilation_score.setProperty(_fromUtf8("value"), 50)
        self.prefer_compilation_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_compilation_score.setObjectName(_fromUtf8("prefer_compilation_score"))
        self.gridLayout.addWidget(self.prefer_compilation_score, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.type_group)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.prefer_soundtrack_score = QtGui.QSlider(self.type_group)
        self.prefer_soundtrack_score.setMaximum(100)
        self.prefer_soundtrack_score.setProperty(_fromUtf8("value"), 50)
        self.prefer_soundtrack_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_soundtrack_score.setObjectName(_fromUtf8("prefer_soundtrack_score"))
        self.gridLayout.addWidget(self.prefer_soundtrack_score, 1, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.type_group)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 4, 1, 1)
        self.prefer_spokenword_score = QtGui.QSlider(self.type_group)
        self.prefer_spokenword_score.setMaximum(100)
        self.prefer_spokenword_score.setProperty(_fromUtf8("value"), 50)
        self.prefer_spokenword_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_spokenword_score.setObjectName(_fromUtf8("prefer_spokenword_score"))
        self.gridLayout.addWidget(self.prefer_spokenword_score, 1, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.type_group)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.prefer_interview_score = QtGui.QSlider(self.type_group)
        self.prefer_interview_score.setMaximum(100)
        self.prefer_interview_score.setProperty(_fromUtf8("value"), 50)
        self.prefer_interview_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_interview_score.setObjectName(_fromUtf8("prefer_interview_score"))
        self.gridLayout.addWidget(self.prefer_interview_score, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.type_group)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.prefer_audiobook_score = QtGui.QSlider(self.type_group)
        self.prefer_audiobook_score.setMaximum(100)
        self.prefer_audiobook_score.setProperty(_fromUtf8("value"), 50)
        self.prefer_audiobook_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_audiobook_score.setObjectName(_fromUtf8("prefer_audiobook_score"))
        self.gridLayout.addWidget(self.prefer_audiobook_score, 2, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.type_group)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 2, 4, 1, 1)
        self.prefer_live_score = QtGui.QSlider(self.type_group)
        self.prefer_live_score.setMaximum(100)
        self.prefer_live_score.setProperty(_fromUtf8("value"), 50)
        self.prefer_live_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_live_score.setObjectName(_fromUtf8("prefer_live_score"))
        self.gridLayout.addWidget(self.prefer_live_score, 2, 5, 1, 1)
        self.label_13 = QtGui.QLabel(self.type_group)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.prefer_remix_score = QtGui.QSlider(self.type_group)
        self.prefer_remix_score.setMaximum(100)
        self.prefer_remix_score.setProperty(_fromUtf8("value"), 50)
        self.prefer_remix_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_remix_score.setObjectName(_fromUtf8("prefer_remix_score"))
        self.gridLayout.addWidget(self.prefer_remix_score, 3, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.type_group)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 3, 2, 1, 1)
        self.prefer_other_score = QtGui.QSlider(self.type_group)
        self.prefer_other_score.setMaximum(100)
        self.prefer_other_score.setSliderPosition(50)
        self.prefer_other_score.setOrientation(QtCore.Qt.Horizontal)
        self.prefer_other_score.setObjectName(_fromUtf8("prefer_other_score"))
        self.gridLayout.addWidget(self.prefer_other_score, 3, 3, 1, 1)
        self.reset_preferred_types_btn = QtGui.QPushButton(self.type_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_preferred_types_btn.sizePolicy().hasHeightForWidth())
        self.reset_preferred_types_btn.setSizePolicy(sizePolicy)
        self.reset_preferred_types_btn.setObjectName(_fromUtf8("reset_preferred_types_btn"))
        self.gridLayout.addWidget(self.reset_preferred_types_btn, 4, 5, 1, 1)
        self.verticalLayout_3.addWidget(self.type_group)
        self.country_group = QtGui.QGroupBox(ReleasesOptionsPage)
        self.country_group.setObjectName(_fromUtf8("country_group"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.country_group)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.country_list = QtGui.QListWidget(self.country_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.country_list.sizePolicy().hasHeightForWidth())
        self.country_list.setSizePolicy(sizePolicy)
        self.country_list.setObjectName(_fromUtf8("country_list"))
        self.horizontalLayout.addWidget(self.country_list)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.add_countries = QtGui.QPushButton(self.country_group)
        self.add_countries.setObjectName(_fromUtf8("add_countries"))
        self.verticalLayout.addWidget(self.add_countries)
        self.remove_countries = QtGui.QPushButton(self.country_group)
        self.remove_countries.setObjectName(_fromUtf8("remove_countries"))
        self.verticalLayout.addWidget(self.remove_countries)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.preferred_country_list = QtGui.QListWidget(self.country_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preferred_country_list.sizePolicy().hasHeightForWidth())
        self.preferred_country_list.setSizePolicy(sizePolicy)
        self.preferred_country_list.setDragEnabled(True)
        self.preferred_country_list.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.preferred_country_list.setObjectName(_fromUtf8("preferred_country_list"))
        self.horizontalLayout.addWidget(self.preferred_country_list)
        self.verticalLayout_3.addWidget(self.country_group)
        self.format_group = QtGui.QGroupBox(ReleasesOptionsPage)
        self.format_group.setObjectName(_fromUtf8("format_group"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.format_group)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.format_list = QtGui.QListWidget(self.format_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_list.sizePolicy().hasHeightForWidth())
        self.format_list.setSizePolicy(sizePolicy)
        self.format_list.setObjectName(_fromUtf8("format_list"))
        self.horizontalLayout_2.addWidget(self.format_list)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.add_formats = QtGui.QPushButton(self.format_group)
        self.add_formats.setObjectName(_fromUtf8("add_formats"))
        self.verticalLayout_2.addWidget(self.add_formats)
        self.remove_formats = QtGui.QPushButton(self.format_group)
        self.remove_formats.setObjectName(_fromUtf8("remove_formats"))
        self.verticalLayout_2.addWidget(self.remove_formats)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.preferred_format_list = QtGui.QListWidget(self.format_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preferred_format_list.sizePolicy().hasHeightForWidth())
        self.preferred_format_list.setSizePolicy(sizePolicy)
        self.preferred_format_list.setDragEnabled(True)
        self.preferred_format_list.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.preferred_format_list.setObjectName(_fromUtf8("preferred_format_list"))
        self.horizontalLayout_2.addWidget(self.preferred_format_list)
        self.verticalLayout_3.addWidget(self.format_group)

        self.retranslateUi(ReleasesOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(ReleasesOptionsPage)

    def retranslateUi(self, ReleasesOptionsPage):
        self.type_group.setTitle(_("Preferred release types"))
        self.label.setText(_("Album"))
        self.label_2.setText(_("Single"))
        self.label_3.setText(_("EP"))
        self.label_7.setText(_("Compilation"))
        self.label_8.setText(_("Soundtrack"))
        self.label_9.setText(_("Spokenword"))
        self.label_10.setText(_("Interview"))
        self.label_11.setText(_("Audiobook"))
        self.label_12.setText(_("Live"))
        self.label_13.setText(_("Remix"))
        self.label_14.setText(_("Other"))
        self.reset_preferred_types_btn.setText(_("Reset all"))
        self.country_group.setTitle(_("Preferred release countries"))
        self.add_countries.setText(_(">"))
        self.remove_countries.setText(_("<"))
        self.format_group.setTitle(_("Preferred release formats"))
        self.add_formats.setText(_(">"))
        self.remove_formats.setText(_("<"))

