# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RenamingEditorOptionsPage(object):
    def setupUi(self, RenamingEditorOptionsPage):
        RenamingEditorOptionsPage.setObjectName("RenamingEditorOptionsPage")
        RenamingEditorOptionsPage.setWindowModality(QtCore.Qt.WindowModal)
        RenamingEditorOptionsPage.setEnabled(True)
        RenamingEditorOptionsPage.resize(453, 552)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RenamingEditorOptionsPage.sizePolicy().hasHeightForWidth())
        RenamingEditorOptionsPage.setSizePolicy(sizePolicy)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(RenamingEditorOptionsPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.file_naming_format_label = QtWidgets.QLabel(RenamingEditorOptionsPage)
        self.file_naming_format_label.setObjectName("file_naming_format_label")
        self.verticalLayout_2.addWidget(self.file_naming_format_label)
        self.frame = QtWidgets.QFrame(RenamingEditorOptionsPage)
        self.frame.setMinimumSize(QtCore.QSize(0, 20))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.file_naming_format = ScriptTextEdit(self.splitter)
        self.file_naming_format.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_naming_format.sizePolicy().hasHeightForWidth())
        self.file_naming_format.setSizePolicy(sizePolicy)
        self.file_naming_format.setMinimumSize(QtCore.QSize(0, 250))
        self.file_naming_format.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.file_naming_format.setTabChangesFocus(False)
        self.file_naming_format.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.file_naming_format.setTabStopWidth(20)
        self.file_naming_format.setAcceptRichText(False)
        self.file_naming_format.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.file_naming_format.setObjectName("file_naming_format")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setContentsMargins(-1, 6, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.example_filename_before_label = QtWidgets.QLabel(self.groupBox)
        self.example_filename_before_label.setObjectName("example_filename_before_label")
        self.horizontalLayout_3.addWidget(self.example_filename_before_label)
        self.example_filename_after_label = QtWidgets.QLabel(self.groupBox)
        self.example_filename_after_label.setObjectName("example_filename_after_label")
        self.horizontalLayout_3.addWidget(self.example_filename_after_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.example_filename_before = QtWidgets.QListWidget(self.groupBox)
        self.example_filename_before.setObjectName("example_filename_before")
        self.horizontalLayout_2.addWidget(self.example_filename_before)
        self.example_filename_after = QtWidgets.QListWidget(self.groupBox)
        self.example_filename_after.setObjectName("example_filename_after")
        self.horizontalLayout_2.addWidget(self.example_filename_after)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.example_filename_sample_files_button = QtWidgets.QPushButton(self.groupBox)
        self.example_filename_sample_files_button.setObjectName("example_filename_sample_files_button")
        self.horizontalLayout.addWidget(self.example_filename_sample_files_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.scripting_documentation_button = QtWidgets.QPushButton(self.groupBox)
        self.scripting_documentation_button.setObjectName("scripting_documentation_button")
        self.horizontalLayout.addWidget(self.scripting_documentation_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.renaming_error = QtWidgets.QLabel(self.groupBox)
        self.renaming_error.setText("")
        self.renaming_error.setAlignment(QtCore.Qt.AlignCenter)
        self.renaming_error.setObjectName("renaming_error")
        self.horizontalLayout.addWidget(self.renaming_error)
        self.file_naming_format_default = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_naming_format_default.sizePolicy().hasHeightForWidth())
        self.file_naming_format_default.setSizePolicy(sizePolicy)
        self.file_naming_format_default.setMinimumSize(QtCore.QSize(0, 0))
        self.file_naming_format_default.setObjectName("file_naming_format_default")
        self.horizontalLayout.addWidget(self.file_naming_format_default)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.file_naming_editor_cancel = QtWidgets.QPushButton(RenamingEditorOptionsPage)
        self.file_naming_editor_cancel.setObjectName("file_naming_editor_cancel")
        self.horizontalLayout_4.addWidget(self.file_naming_editor_cancel)
        self.file_naming_editor_save = QtWidgets.QPushButton(RenamingEditorOptionsPage)
        self.file_naming_editor_save.setObjectName("file_naming_editor_save")
        self.horizontalLayout_4.addWidget(self.file_naming_editor_save)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)

        self.retranslateUi(RenamingEditorOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(RenamingEditorOptionsPage)

    def retranslateUi(self, RenamingEditorOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.file_naming_format_label.setText(_("Name files like this"))
        self.groupBox.setTitle(_("Examples"))
        self.example_filename_before_label.setText(_("Before"))
        self.example_filename_after_label.setText(_("After"))
        self.example_filename_sample_files_button.setText(_("Renew examples"))
        self.scripting_documentation_button.setText(_("Scripting Documentation"))
        self.file_naming_format_default.setText(_("Default"))
        self.file_naming_editor_cancel.setText(_("Cancel"))
        self.file_naming_editor_save.setText(_("Save"))
from picard.ui.widgets.scripttextedit import ScriptTextEdit
