# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/tageditor.ui'
#
# Created: Thu Sep 15 13:39:10 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_TagEditorDialog(object):
    def setupUi(self, TagEditorDialog):
        TagEditorDialog.setObjectName(_fromUtf8("TagEditorDialog"))
        TagEditorDialog.resize(535, 436)
        self.vboxlayout = QtGui.QVBoxLayout(TagEditorDialog)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.tabWidget = QtGui.QTabWidget(TagEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.tab_4)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(9)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.tags = QtGui.QTreeWidget(self.tab_4)
        self.tags.setRootIsDecorated(False)
        self.tags.setObjectName(_fromUtf8("tags"))
        self.vboxlayout1.addWidget(self.tags)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ratingLabel = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ratingLabel.sizePolicy().hasHeightForWidth())
        self.ratingLabel.setSizePolicy(sizePolicy)
        self.ratingLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.ratingLabel.setObjectName(_fromUtf8("ratingLabel"))
        self.horizontalLayout.addWidget(self.ratingLabel)
        self.rating = RatingWidget(self.tab_4)
        self.rating.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rating.sizePolicy().hasHeightForWidth())
        self.rating.setSizePolicy(sizePolicy)
        self.rating.setMinimumSize(QtCore.QSize(0, 0))
        self.rating.setObjectName(_fromUtf8("rating"))
        self.horizontalLayout.addWidget(self.rating)
        self.vboxlayout1.addLayout(self.horizontalLayout)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.tags_add = QtGui.QPushButton(self.tab_4)
        self.tags_add.setObjectName(_fromUtf8("tags_add"))
        self.hboxlayout.addWidget(self.tags_add)
        self.tags_edit = QtGui.QPushButton(self.tab_4)
        self.tags_edit.setObjectName(_fromUtf8("tags_edit"))
        self.hboxlayout.addWidget(self.tags_edit)
        self.tags_delete = QtGui.QPushButton(self.tab_4)
        self.tags_delete.setObjectName(_fromUtf8("tags_delete"))
        self.hboxlayout.addWidget(self.tags_delete)
        spacerItem = QtGui.QSpacerItem(151, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.vboxlayout1.addLayout(self.hboxlayout)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.tab_2)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setMargin(9)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.artwork_list = QtGui.QListWidget(self.tab_2)
        self.artwork_list.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.artwork_list.setIconSize(QtCore.QSize(170, 170))
        self.artwork_list.setMovement(QtGui.QListView.Static)
        self.artwork_list.setFlow(QtGui.QListView.LeftToRight)
        self.artwork_list.setProperty(_fromUtf8("isWrapping"), False)
        self.artwork_list.setResizeMode(QtGui.QListView.Fixed)
        self.artwork_list.setSpacing(10)
        self.artwork_list.setViewMode(QtGui.QListView.IconMode)
        self.artwork_list.setObjectName(_fromUtf8("artwork_list"))
        self.vboxlayout2.addWidget(self.artwork_list)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.vboxlayout3 = QtGui.QVBoxLayout(self.tab_5)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setMargin(9)
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.info = QtGui.QLabel(self.tab_5)
        self.info.setText(_fromUtf8(""))
        self.info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.info.setWordWrap(True)
        self.info.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.info.setObjectName(_fromUtf8("info"))
        self.vboxlayout3.addWidget(self.info)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.vboxlayout.addWidget(self.tabWidget)
        self.buttonbox = QtGui.QDialogButtonBox(TagEditorDialog)
        self.buttonbox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonbox.setObjectName(_fromUtf8("buttonbox"))
        self.vboxlayout.addWidget(self.buttonbox)

        self.retranslateUi(TagEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TagEditorDialog)
        TagEditorDialog.setTabOrder(self.tags, self.tags_add)
        TagEditorDialog.setTabOrder(self.tags_add, self.tags_delete)
        TagEditorDialog.setTabOrder(self.tags_delete, self.tabWidget)
        TagEditorDialog.setTabOrder(self.tabWidget, self.artwork_list)

    def retranslateUi(self, TagEditorDialog):
        self.tags.headerItem().setText(0, _("Name"))
        self.tags.headerItem().setText(1, _("Value"))
        self.ratingLabel.setText(_("Rating:"))
        self.tags_add.setText(_("&Add..."))
        self.tags_edit.setText(_("&Edit..."))
        self.tags_delete.setText(_("&Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _("&Metadata"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("A&rtwork"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _("&Info"))

from picard.ui.ratingwidget import RatingWidget
