# -*- coding: utf-8 -*-
# Automatically generated - don't edit.
# Use `python setup.py update_constants` to update it.

MB_ATTRIBUTES = {
    u'DB:cover_art_archive.art_type/name:001': u'Front',
    u'DB:cover_art_archive.art_type/name:002': u'Back',
    u'DB:cover_art_archive.art_type/name:003': u'Booklet',
    u'DB:cover_art_archive.art_type/name:004': u'Medium',
    u'DB:cover_art_archive.art_type/name:005': u'Obi',
    u'DB:cover_art_archive.art_type/name:006': u'Spine',
    u'DB:cover_art_archive.art_type/name:007': u'Track',
    u'DB:cover_art_archive.art_type/name:008': u'Other',
    u'DB:cover_art_archive.art_type/name:009': u'Tray',
    u'DB:cover_art_archive.art_type/name:010': u'Sticker',
    u'DB:cover_art_archive.art_type/name:011': u'Poster',
    u'DB:cover_art_archive.art_type/name:012': u'Liner',
    u'DB:cover_art_archive.art_type/name:013': u'Watermark',
    u'DB:medium_format/name:001': u'CD',
    u'DB:medium_format/name:002': u'DVD',
    u'DB:medium_format/name:003': u'SACD',
    u'DB:medium_format/name:004': u'DualDisc',
    u'DB:medium_format/name:005': u'LaserDisc',
    u'DB:medium_format/name:006': u'MiniDisc',
    u'DB:medium_format/name:007': u'Vinyl',
    u'DB:medium_format/name:008': u'Cassette',
    u'DB:medium_format/name:009': u'Cartridge',
    u'DB:medium_format/name:010': u'Reel-to-reel',
    u'DB:medium_format/name:011': u'DAT',
    u'DB:medium_format/name:012': u'Digital Media',
    u'DB:medium_format/name:013': u'Other',
    u'DB:medium_format/name:014': u'Wax Cylinder',
    u'DB:medium_format/name:015': u'Piano Roll',
    u'DB:medium_format/name:016': u'DCC',
    u'DB:medium_format/name:017': u'HD-DVD',
    u'DB:medium_format/name:018': u'DVD-Audio',
    u'DB:medium_format/name:019': u'DVD-Video',
    u'DB:medium_format/name:020': u'Blu-ray',
    u'DB:medium_format/name:021': u'VHS',
    u'DB:medium_format/name:022': u'VCD',
    u'DB:medium_format/name:023': u'SVCD',
    u'DB:medium_format/name:024': u'Betamax',
    u'DB:medium_format/name:025': u'HDCD',
    u'DB:medium_format/name:026': u'USB Flash Drive',
    u'DB:medium_format/name:027': u'slotMusic',
    u'DB:medium_format/name:028': u'UMD',
    u'DB:medium_format/name:029': u'7" Vinyl',
    u'DB:medium_format/name:030': u'10" Vinyl',
    u'DB:medium_format/name:031': u'12" Vinyl',
    u'DB:medium_format/name:033': u'CD-R',
    u'DB:medium_format/name:034': u'8cm CD',
    u'DB:medium_format/name:035': u'Blu-spec CD',
    u'DB:medium_format/name:036': u'SHM-CD',
    u'DB:medium_format/name:037': u'HQCD',
    u'DB:medium_format/name:038': u'Hybrid SACD',
    u'DB:medium_format/name:039': u'CD+G',
    u'DB:medium_format/name:040': u'8cm CD+G',
    u'DB:medium_format/name:041': u'CDV',
    u'DB:medium_format/name:042': u'Enhanced CD',
    u'DB:medium_format/name:043': u'Data CD',
    u'DB:medium_format/name:044': u'DTS CD',
    u'DB:medium_format/name:045': u'Playbutton',
    u'DB:medium_format/name:046': u'Music Card',
    u'DB:medium_format/name:047': u'DVDplus',
    u'DB:medium_format/name:048': u'VinylDisc',
    u'DB:medium_format/name:049': u'3.5" Floppy Disk',
    u'DB:medium_format/name:050': u'Edison Diamond Disc',
    u'DB:medium_format/name:051': u'Flexi-disc',
    u'DB:medium_format/name:052': u'7" Flexi-disc',
    u'DB:medium_format/name:053': u'Shellac',
    u'DB:medium_format/name:054': u'10" Shellac',
    u'DB:medium_format/name:055': u'12" Shellac',
    u'DB:medium_format/name:056': u'7" Shellac',
    u'DB:medium_format/name:057': u'SHM-SACD',
    u'DB:medium_format/name:058': u'Pathé disc',
    u'DB:medium_format/name:059': u'VHD',
    u'DB:medium_format/name:060': u'CED',
    u'DB:medium_format/name:061': u'Copy Control CD',
    u'DB:release_group_primary_type/name:001': u'Album',
    u'DB:release_group_primary_type/name:002': u'Single',
    u'DB:release_group_primary_type/name:003': u'EP',
    u'DB:release_group_primary_type/name:011': u'Other',
    u'DB:release_group_primary_type/name:012': u'Broadcast',
    u'DB:release_group_secondary_type/name:001': u'Compilation',
    u'DB:release_group_secondary_type/name:002': u'Soundtrack',
    u'DB:release_group_secondary_type/name:003': u'Spokenword',
    u'DB:release_group_secondary_type/name:004': u'Interview',
    u'DB:release_group_secondary_type/name:005': u'Audiobook',
    u'DB:release_group_secondary_type/name:006': u'Live',
    u'DB:release_group_secondary_type/name:007': u'Remix',
    u'DB:release_group_secondary_type/name:008': u'DJ-mix',
    u'DB:release_group_secondary_type/name:009': u'Mixtape/Street',
    u'DB:release_group_secondary_type/name:010': u'Demo',
}
