name: Validate AppStream

on:
  push:
    paths:
    - '.github/workflows/validate-appstream.yml'
    - 'org.musicbrainz.Picard.appdata.xml.in'
    - 'po/appstream/*.po'
    - 'NEWS.md'
    - 'setup.py'
  pull_request:

jobs:
  validate-appstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install appstream
      run: |
        sudo apt-get update
        sudo apt-get install appstream gettext
    - name: Validate AppStream metadata
      run: |
        python setup.py build_appdata
        appstreamcli validate --pedantic --explain org.musicbrainz.Picard.appdata.xml
