name: Validate XDG metadata

on:
  push:
    paths:
    - '.github/workflows/validate-xdg-metadata.yml'
    - 'org.musicbrainz.Picard.appdata.xml.in'
    - 'org.musicbrainz.Picard.desktop.in'
    - 'po/appstream/*.po'
    - 'NEWS.md'
    - 'setup.py'
  pull_request:

jobs:
  validate-xdg-metadata:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install utils
      run: |
        sudo apt-get update
        sudo apt-get install appstream desktop-file-utils gettext
        pip install setuptools
    - name: Validate AppStream metadata
      run: |
        python setup.py build_appdata
        appstreamcli validate --pedantic --explain org.musicbrainz.Picard.appdata.xml
    - name: Validate desktop file
      run: |
        python setup.py build_desktop_file
        desktop-file-validate org.musicbrainz.Picard.desktop
